### ISSUE TITLE
Изменение в шаблоне BASE процедура open и update

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#100]
В рамках #99 
Привет, в шаблоне BASE  в процедуре OPEN и UPDATE прошу убрать выделенное жирным 

> **Open** TT: #348 032
> Status: В ожидании
> ## : Сергей; Не работает интернет, отсутствует подключение к сети.
> ### : Хорошая услуга
> 
> CID: D2000000

Должно получиться так:

> TT: #348 032
> Status: В ожидании
> ## : Сергей; Не работает интернет, отсутствует подключение к сети.
> ### : Хорошая услуга
> 
> CID: D2000000

**Comment by panches** [comment]
Слово Open?

**Comment by VsMoroz** [comment]
КО :) Да !

**Comment by panches** [comment]
Убрал, v1.9.23

**Comment by VsMoroz** [comment]
В шаблоне  при процедуре UPDATE не пропал open, а должен бы

**Comment by panches** [comment]
исправил, версию не менял
