### ISSUE TITLE
Изменение в шаблоне BASE процедура close

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#101]
В рамках #99
В шаблоне BASE в процедуре CLOSE прошу провести изменения с  выделеным жирным 

**Сейчас вот так:**

> TT: #347 821 - **Close** 
> 10:57 02.03.16 (UTC+2)
> Причина: -
> 
> **Open TT**
> Status: В работе
> 15:28 29.02.16
> ## :  Не работает канал
> ### :  Нормальный банк нормальная услуга
> 
> CID: D0000001

**Сделать вот так:**

> TT: #347 821 - is closed 
> 10:57 02.03.16 (UTC+2)
> Причина: -
> 
> TT - was opened
> Status: В работе
> 15:28 29.02.16
> ## :  Не работает канал
> ### :  Нормальный банк нормальная услуга
> 
> CID: D0000001

**Comment by VsMoroz** [comment]
ой вот в этой часте  убери дефис тоже, что бы получилось вот так:

TT was opened
Status: В работе
15:28 29.02.16

**Comment by panches** [comment]
Изменил, v1.9.23

**Comment by VsMoroz** [comment]
Прошу в шаблонах BASE и BASE_EN процедура CLOSE убрать  строчку Status: В работе (выделено жирным)

TT: #347 821 - is closed
10:57 02.03.16 (UTC+2)
Причина: 

TT - was opened
**Status: В работе**
15:28 29.02.16

##: Не работает канал

###: Нормальный банк нормальная услуга
CID: D0000001

**Comment by panches** [comment]
убрал строчку Status,  v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Спасибо !

**Comment by VsMoroz** [comment]
Прошу в шаблоне BASE, в процедуре close заменить : 
TT was opened на TT был открыт
TT: #348 748 is closed  на TT: #348 748 закрыт

**Comment by VsMoroz** [comment]
А так же в шаблоне BASE  процедурах open и update заменить:
Status: в ожидании на  Статус: в ожидании

**Comment by panches** [comment]
заменил, v1.9.23(не менял)
