### ISSUE TITLE
Создание нового шаблона BASE_EN

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#102]
Копируем шаблон email оповещения BASE в том виде в котором он есть сейчас после изменений сделанных в  #99. Создаем из него шаблон BASE_EN  (по следам #68)
По этому шаблону будем оповещать англоязычных потребителей.

**Comment by VsMoroz** [comment]
Тоесть сейчас задача сделать ответвление, если у клиента стоит BASE_EN - то оповещение происходило по нему, дальше начнем менять BASE_EN - я пока дублирую английским языком текущие справочники, пришлю их почтой

**Comment by VsMoroz** [comment]
В процедурах open и update, при построении email значение статуса (выделенно жирным) подтягивать из tab_status_tt.forCustomer_en (ранее подтягивалось из tab_status_tt.forCustomer)

TT: #348 119
Status: **В ожидании**

**Comment by panches** [comment]
Заменил, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Это уже на завтра убери пожалуйста в профилях BASE и BASE_EN  в процедуре close  вот это дефис между номером тт и "is closed"

В профиле BASE_EN в процедуре close замени слово "Причина:" на "The reason(briefly):" и саму причину подтягивай из  classification.formal_version_en (ранее она подтягивалась из classification.formal_version)

> TT: #347 994 - is closed 
> 19:14 02.03.16 (UTC+2)
> Причина: Авария у пользователя

Новую таблицу classification сейчас пришлю.

**Comment by panches** [comment]
Исправил, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Добавь в выпадающий список в каталоге партнеров профиль BASE_EN (напомню по умолчанию значение этого поля  при создании нового парнтера должно быть  BASE)

**Comment by VsMoroz** [comment]
Не забудь расширить значение  tab_klients.emailtemplate c varchar(4) до varchar(7)

**Comment by VsMoroz** [comment]
Ниже процитированное нужно было сделать только для шаблона BASE_EN
Для шаблона UGBK и BASE - верни все обратно.

> В процедурах open и update, при построении email значение статуса (выделенно жирным) подтягивать из tab_status_tt.forCustomer_en (ранее подтягивалось из tab_status_tt.forCustomer)
> 
> TT: #348 119
> Status: В ожидании

**Comment by panches** [comment]
Ок, я уберу. Но давай сделаем так: опиши отдельно для каждого, как долже выглядеть UGBK, BASE и BASE_EN. И тогда таких проколов не будет.

**Comment by panches** [comment]
В список добавил BASE_EN, v5.46.32

**Comment by panches** [comment]
исправил, v1.9.23(не менял)

**Comment by VsMoroz** [comment]
Давай выработаем такое правило этот ишью называется Создание нового шаблона BASE_EN   все изменения которые в  нем описываются по умолчанию касаюся только профиля BASE_EN. Если вдруг такое же изменение нужно сделать в чем то другом, я на это буду  или создавать отдельный ишью или в тексте буду делать акцент что и для профиля такого то сделай это же изменение.

**Comment by VsMoroz** [comment]
В профиле BASE_EN в процедуре close  вставь пробел можду reason и (, пример: 
"The reason (briefly):"

**Comment by VsMoroz** [comment]
И проверь пожалуйста в профиле  BASE_EN процедуры close open update слово TT оно должно быть из английских букв :)

**Comment by panches** [comment]
"Пробел" добавил (в CID тоже), буквы ТТ в EN раскладке. Версию не менял.

**Comment by VsMoroz** [comment]
Шаблон BASE_EN процедура open update close  сделать транслитерацию названия услуги (выделенно жирным в примере ниже):

Использовать хранимые процедуры _fs_transliterate_2 и proper , пример запроса который выполнит  транслитерацию:  SELECT proper(_fs_transliterate_2("здесь_транслитерируемый_текст"))

> TT: #348 350
> Status: processing
> 
> ##: от noc@bank.us Не работает предоставляемая Вами услуга
> 
> ###: **Банк, ПД, 2М, (Сумы, ул.Независимости 14 - ул. Лушпы, 33)** (CID: D062059)

**Comment by VsMoroz** [comment]
Задача на понедельник : 
В профиле BASE_EN в процедуре close
заменить фразу was open на was started
заменить фразу is closed на is finished

**Comment by panches** [comment]
заменил, v1.9.23(не менял)

**Comment by VsMoroz** [comment]
Привет ! 
Сделай пожайлуста транслитерацию типа услуги для писем которые отправляются на  ТТ  по шаблону BASE_EN  и которые открыты на ОК

**Comment by panches** [comment]
В ОК есть: клиент + город + адрес. А тип услуги это где?

**Comment by VsMoroz** [comment]
Нужно транслитерировать строчку которая после трех диезов ###:

**Comment by VsMoroz** [comment]
ТОлько в шаблоне BASE_EN

**Comment by panches** [comment]
выполнил, v1.9.23(не менял)

**Comment by VsMoroz** [comment]
В шаблоне BASE_EN  в процедуре close  прошу заменить The reason (briefly): на The reason:

**Comment by panches** [comment]
заменил, v1.9.23(не менял)

**Comment by VsMoroz** [comment]
Следующая итерация :) нет предела совершенству:

В шаблоне BASE_EN в процедуре close прошу заменить "The reason:" на  "The cause:"

Спасибо !

**Comment by panches** [comment]
заменил, v1.9.24(не менял)

**Comment by VsMoroz** [comment]
Еще работаю над переводом справочников с причинами аварий, есть 4 варианта ;)

**Comment by VsMoroz** [comment]
В шаблоне BASE_EN в процедуре close прошу заменить: 
"TT: #349 950 is finished" заменить на "TT: #349 950 is closed"
"TT was started" заменить на "TT was opened"

**Comment by panches** [comment]
заменил, v1.9.24(не менял)

**Comment by VsMoroz** [comment]
Добавил в официальные версии перевод на английский язык, нормально получилось.
