### ISSUE TITLE
Перенести CID в шаблонах BASE и BASE_EN  оповещения  в процедурах  open update и close

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#103]
В шаблонах BASE и BASE_EN  оповещения  в процедурах  open update и close

**Перенести CID  что бы стало вот так**:
### : (CID: D0000001) Нормальный банк нормальная услуга

**Ранее было вот так:**
### : Нормальный банк нормальная услуга

CID: D0000001

Ишью для группировки этих изменений #99

**Comment by panches** [comment]
выполнил, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Между закрывающей скобкой и началом описания услуги два пробела, сделай пусть будет один.

(CID: D0000001) Нормальный

**Comment by panches** [comment]
Исправил, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Я смотрю что в шаблоне UGBK  CID тоже переехал, верни обратно, в шаблоне UGBK все должно быть по старому. В Шаблонах BASE и BASE_EN он должен переехать. Пришлю пример почтой

**Comment by panches** [comment]
Исправил, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Так же смотрю что CID в шаблоне BASE_EN  находится не на нужном месте (на старом) пример письмом.

**Comment by panches** [comment]
Подправил шаблон BASE_EN, v1.9.23 (не менял)

**Comment by VsMoroz** [comment]
Как в том известном ролике из Харькова, "Все фигня Миша давай заново" ;)

Не нравится мне новое расположение  CID.
Прошу для профилей BASE и BASE_EN для процедур open update close   перенести CID  в конец надписи о услуге (без пробелов) пример:
Банк, ПД, 1М, (Киев, Хрещатик 21 - Симферополь, ул Сечевых стрельцов 12)(CID: D0000001)

**Comment by panches** [comment]
перенес, v1.9.23(не менял)

**Comment by VsMoroz** [comment]
Отлично, спасибо
