### ISSUE TITLE
Изменить шаблон использующийся при ТТ на tab_on =0  что бы использовался BASE

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#104]
Тоже задача на понедельник, что бы не забыть:
Прошу перенастроить серверную часть  процедуры open update  и close для ТТ у которых tab_on = 0 или 4  (кстати где еще используется шаблон который сейчас действует для 0 ?) что бы использовался  шаблон BASE а то там сейчас используется похоже шаблон UGBK не очень все хорошо выглядит, пример пришлю почтой.

**Comment by panches** [comment]
Пусть ИмяКлиента = name
Тогда Шаблоны:
0,1 = name
2,3,4,5,6 = name (без первых 5-ти символов)
7 = сложная комбинация разных запросов и их полей

Можно более конкретно указать где проблема?

**Comment by VsMoroz** [comment]
Работает после последних доработок, хотя я думаю мы к этому вопросу еще вернемся. Ну это будет потом.
