### ISSUE TITLE
Подсказывать инженеру что необходимо добавить в сообщение English версию при добавление записи в ТТ с "Отослать что сделанно по email клиенту"

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#105]
Основная идея: 
В форме добавления записи в ТТ: 
- если ТТ (или подчиненные под него) имеют email получателей и среди них есть получатели с BASE_EN  - то показать слово En возле галочки "Отослать по Email клиенту"
- если пользователь поставил галочку "Отослать по Email клиенту" проверить нет ли получателей с BASE_EN - если есть, проверить добавляемую запись - в ней должна быть английская версия. Если английской версии в записи нет - вывести пользователю предупреждение и предложить добавить английскую версию.

Определять английскую версию будем анализируя добавляемую  запись: если в ней есть минимум  три слова с минимум 2 буквами каждое  на английском - тогда считаем что английская версия есть.

Готовлю запрос который будет проверять есть ли англоязычный получатели у этого или подчиненных ТТ, если запрос вернет больше 0 - то есть. Если 0  то нет.

В коннекте к #102

**Comment by VsMoroz** [comment]
Я сформировал запрос проверяющий ТТ  на предмет нужно ли в комментарий добавить английскую версию (вот  https://github.com/VsMoroz/tt-system-data/commit/84ad1c8ce476f2ef365992826befb8146f3d0baa)

Сможешь сделать по такому алгоритму  ? Пользователь набирает запись нажимает кнопку Добавить запись, система проверяет если нужно добавить English - оно выводит предупреждение 

"В получателях присутствуют пользователи из других стран, добавьте в конец записи англоязычную версию сообщения"

А также в конец уже написанной записи добавляет "(English:  )
**Пример:**
"Обрыв оптического волокна был восстановлен, проверьте пожайлуста восстановление услуги."

После предупреждени в запись добавится шаблон и она станет выглядеть так:
"Обрыв оптического волокна был восстановлен, проверьте пожайлуста восстановление услуги.(English )"

И что бы приложение анализировало, если пользователь повторно  жмет кнопку добавить и программа не почувствовала что английская версия появилась, что бы программа так же проанализировала и если в записи уже есть слово English то не добавлять повторно в конце записи  "English ( )"

**Comment by panches** [comment]
выполнил, v5.46.33

**Comment by VsMoroz** [comment]
Работает, закрываю ишью
