### ISSUE TITLE
Добавлять английскую версию записей с transition 63 в ТТ у которого клиент имеет BASE_EN профиль

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#106]
Добавить проверку при вставлении записи вТТ с transition = 63,  если у ТТ профиль оповещени BASE_EN то поле zapisi_trubl_tic.desc_zapisi формировать так:

zapisi_trubl_tic.desc_zapisi = The supposed cause is: classification.formal_version_en, estimated time to restore  trubl.estimate_of_end(в формате '12:30 13.02.2016')

Если профиль email оповещения другой (или его вообще нет) то поле формировать так как это делается сейчас, а именно:
zapisi_trubl_tic.desc_zapisi = Предварительная причина: classification.formal_version, рассчетный срок окончания trubl.estimate_of_end(в формате '12:30 13 февраля 2016')

В коннекте с #102 и #83

**Comment by VsMoroz** [comment]
Сань, я чуть поменял перевод в техзадании  (изменил первое сообщение в этом ишью) английская версия пусть звучит так:

zapisi_trubl_tic.desc_zapisi = The supposed cause is: classification.formal_version_en, estimated time to restore  trubl.estimate_of_end(в формате '12:30 13.02.2016')

**Comment by panches** [comment]
добавил, v5.46.34

**Comment by VsMoroz** [comment]
Привет ! 
Следующая итерация :) 
Прошу заменить "The supposed cause is:" на  "Probable cause:" вот в здесь:

zapisi_trubl_tic.desc_zapisi = The supposed cause is: classification.formal_version_en, estimated time to restore trubl.estimate_of_end(в формате '12:30 13.02.2016')

После замены вставляемая запись должна выглядеть так:
zapisi_trubl_tic.desc_zapisi = Probable cause: classification.formal_version_en, estimated time to restore trubl.estimate_of_end(в формате '12:30 13.02.2016')
Спасибо !

**Comment by panches** [comment]
заменил, v5.46.35

**Comment by VsMoroz** [comment]
Работает, тоже закрывают

**Comment by VsMoroz** [comment]
Мы забыли что при подчинении ТТ с профилем BASE_EN записи с transition 63 тоже нужно добавлять на английском. А то ща на русском добавляетс, пример почтой пришлю

**Comment by panches** [comment]
добавил, v5.46.37

**Comment by VsMoroz** [comment]
Спасибо работает
