### ISSUE TITLE
Помогать пользователю выбирать рабочее место при   залогинивании в систему

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#107]
При залогинивании мы пользователю показываем форму в которой он должен ввести логин, пароль, а так же выбрать рабочее место в поле Group.

Необходимо добработать  и по умолчанию подставлять значение в Group по такому алгоритму:

Смотрим в какое рабочее место в прошлый раз  выполнял вход  этот пользователь за последние три недели.

Если нет информации - тогда значение по умолчанию  такое как сейчас (группа не выбрана)
Если есть информация  - то значение в поле Group принимает значение последнего  рабочего места в которое он залогинился прошлый раз

**Comment by VsMoroz** [comment]
Для выполнения этой задачи нам нужно модернизировать запрос который логирует в БД факт входа пользователя. Сейчас он фиксирует только что пользователь залогинился, но не фиксирует куда, нужно что бы фиксировал.
Пришли почтой какой там сейчас запрос для вставки в таблицу   tab_audit_trail
Должно быть что то с INSERT 
Пришли  почтой.

**Comment by VsMoroz** [comment]
Модернизируем, добавим сюда информацию в какое место логинится пользователь:

INSERT INTO tab_audit_trail (logger, user, action, table, field, keyvalue, oldvalue , newvalue  ) 
                                        VALUE ("client", "'+ Nik_id+'", "login", "expworkers","logged","expworkers.id того рабочего места куда логинится пользователь","значение которое есть сейчас в expworkers.logged","tab_access.id пользователя который логинится" )

**Comment by panches** [comment]
добавил, v5.46.35

**Comment by VsMoroz** [comment]
Ок, эта модернизация позволит нам сохранять историю кто в какое рабочее место логинился, пусть будет для логирования  и дальнейших автоматизаций.

Для выполнения текущего ишью необходимо запоминань в файлик на локальном компьютере в какой рабочее место логинится пользователь expworkers.id (перезаписывать его при каждом новом залогинивании)

А при запуске формы в которую вводится логин и пароль, считывать это значение и в выпадающем списке рабочих мест,  сразу выбирать это считанное из файлика значение в спике. 

Пользователь или согласится с этим просто введя логин и пароль, или  выберет другое рабочее место.

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Все гуд, работает. Только пропала возможность заходить без прикрепления к рабочему месту.
Добавь в списке Group первым в списке "-" выбрав который пользователь будет логиниться без прикрепления к рабочему месту

**Comment by panches** [comment]
подправил, v5.46.35

**Comment by VsMoroz** [comment]
Спасибо, все работает
