### ISSUE TITLE
Устранить проблему с подвисанием БД при формировании еженедельного отчета по СТОП

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#109]
Пока известно что он есть и что база по этому запросу просто пишет что она шлет информацию клиенту и на другие запросы информации не отвечает.
Поисследуем еще в будние дни.

**Comment by VsMoroz** [comment]
Добавил индекс полю corp_retail в табличке в которой хранятся даннные по услугам сторонних операторов. Запрос заработал.

**Comment by VsMoroz** [comment]
Повторилась проблема, исследую причины.

**Comment by panches** [comment]
Может подойти по другому: там 3000+ записей в окне, сервер загибается пока их сформирует в час пик. Может отображать их частями, поставить фильтр (временной или еще какой-то)?

**Comment by VsMoroz** [comment]
Та этот запрос запускатся в 6:00 утра. Нужно тюнить производительность сервера, там либо ему мало места под память либо выделенного места на диске недостаточно.

**Comment by VsMoroz** [comment]
Для истории, убрал индекc по полю timestamp  в таблице логирования, строит часть с рассчетами опес и капекс куда медленне, но не виснет. Ок. до разбирательства чего там sql серверу не хватает.

**Comment by VsMoroz** [comment]
закрываю т.к. все работает
