### ISSUE TITLE
Закладка  Аварийки -> все выезды, добавить сортировку по полям

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#112]
Прошу добавить в закладку функционал сортировки по полям, что бы при нажатии на название поля производилась сортировка по возростанию или по убыванию

И что бы при сортировке учитывалось сотояние фильтров которые есть на этой форме.

Спасибо.

**Comment by panches** [comment]
выполнил, v5.46.38 (кроме поля "Тип наряда")

**Comment by VsMoroz** [comment]
Спасибо !
