### ISSUE TITLE
Изменять статус ОК, при изменении статуса СК

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#113]
При изменении статуса  СК, выполнить изменение, запомнить новое просвоенное net_data.status_d  значение.

Сделать проверку есть ли в ОК А и ОК Б  этой услуги, другие услуги со статусом в эксплуатации.

_Проверить офис Б:_

> SELECT COUNT(*)
>       FROM net_data
>       WHERE net_data.status_d = '2' AND net_data.office_b = 'значение из net_data.office_b'

_Проверить офис A:_

> SELECT COUNT(*)
>       FROM net_data
>       WHERE net_data.status_d = '2' AND net_data.office_a = 'значение из net_data.office_a'

Если  запрос проверка по офису А или офису Б  - вернули значение = '0' тогда этому офису в  office_kli.status_d вписать такое же значение какое было вписанно в net_data.status_d   СК

**Comment by VsMoroz** [comment]
При изменении статуса  СК, выполнить изменение, запомнить новое просвоенное net_data.status_d  значение.

Сделать проверку есть ли в ОК А и ОК Б  этой услуги, другие услуги со статусом в эксплуатации.

_Проверить офис Б:_

> SELECT COUNT(*)
> 		FROM net_data
> 		WHERE net_data.status_d = '2' AND net_data.office_b = 'значение из net_data.office_b'

_Проверить офис A:_

> SELECT COUNT(*)
> 		FROM net_data
> 		WHERE net_data.status_d = '2' AND net_data.office_a = 'значение из net_data.office_a'

Если  запрос проверка по офису А или офису Б  - вернули значение = '0' тогда этому офису в  office_kli.status_d вписать такое же значение какое было вписанно в net_data.status_d   СК

**Comment by VsMoroz** [comment]
Только внимательно к реализации отнесись, будет плохо если изза ошибки система попереводит главные офисы из эксплуатации.

**Comment by VsMoroz** [comment]
Так же не забудь при изменении status_d ОК применить ту же логику которая работает при выводе из эксплуатации ОК в форме редактирования ОК - в поле out_exp вставляется дата вывода из эксплуатации

**Comment by panches** [comment]
Может запросы немного расширить:
SELECT COUNT(_)
FROM net_data
WHERE net_data.status_d = '2' AND (net_data.office_b = 'значение из net_data.office_b' or net_data.office_a = 'значение из net_data.office_b')
и
SELECT COUNT(_)
FROM net_data
WHERE net_data.status_d = '2' AND (net_data.office_a = 'значение из net_data.office_a' or
net_data.office_b = 'значение из net_data.office_a') 
?

**Comment by VsMoroz** [comment]
Да давай такой задействуем

**Comment by panches** [comment]
выполни, v5.46.38

**Comment by VsMoroz** [comment]
Работает, гуд, спасибо
