### ISSUE TITLE
Назначение ТТ на группу, когда в группе нет ни одного доступного рабочего места

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#115]
Привет ! 
Присутствует ошибка при назначении ТТ на группу если в группе нет ни одного доступного рабочего места.

Система выводит предупреждение что в группе нет ни одного свободного места но сам ТТ на группу назначает  в user_id прописывает 2200000 (тоесть ни кому он не принадлежит)

Прошу передалать что бы если в группе нет ни одного свободного места, по прежнему выводилось об этом предупреждение и user_id не менялся, тоесть ТТ оставался закрепленным за текущим рабочим местом.

**Comment by panches** [comment]
исправил ошибку, v5.46.39

**Comment by VsMoroz** [comment]
Решен спасибо
