### ISSUE TITLE
В ClientDB добавить страничку статистики для анализа  показателей по SLA

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#117]
Прошу добавить в интерфейс  открываемый по кнопке "Статистика" закладку "Статистика по SLA"
Тех. задание и запросы пишу.

**Comment by VsMoroz** [comment]
Прошу добавить в интерфейс открываемый по кнопке "Статистика" закладку "Статистика по SLA", в форму добавить поля:

-Дата начала периода анализа "С" (по умолчанию равна now()-31 day)
-Дата окончания периода анализа "До"
-тип SLA (выпадающее меню по аналогии с "Фильтр по статусу ТТ" в Активных ТТ, где , будут значения из запроса):

> SELECT concat(name," (",lbl,")") FROM tab_sla_net_data ORDER BY name ASC  // если нужно добавь id в результат выдачи.

-Кнопку "Выбрать"
При нажатии на кнопку выбрать, по выбранным SLA  и за выбранный период  выбираются закрытые ТТ по ним заполняется табличка, в форме.
Пример таблички с запросами я приаттачу ниже в этом ишью

*следующим шагом мы добавим несколько кнопок которые позволят за выбранные приод вытянуть более детальную информацию  виде файла.

**Comment by VsMoroz** [comment]
Добавил табличку которую нужно отобразить в интерфейсе и запросы как получить цифры

**Comment by panches** [comment]
Выполнил, v5.46.43

**Comment by VsMoroz** [comment]
Как то выглядит не очень (слева и сверху границы таблицы обрезанны, справа и снизу есть) , может сделай отображение в виде текстовых лейб коотрые разместить одна под одной в виде строчек ? 

Прошу напротив каждого из полей:
- Всего количество ТТ по выбранным SLA:
- Количество ТТ с нарушением сроков устранения:
- Количество выездов по выбранным SLA:
- Всего (количество) услуг с выбранными SLA:

добавить или кнопку или  "типа" гиперссылку подчеркнутый синий текст с надписью "Детальнее"
При нажатии на "Детальнее" выполнится новый запрос по сбору данных, откроется эксель файлик и в него вставится результат.

Запросы в коммите ниже этой записи там напротив описания каждого запроса добавлено слова "# Детальнее:"

**Comment by panches** [comment]
Выполнил, версию не менял.
На странице два варианта, выбери один.

**Comment by VsMoroz** [comment]
Пусть будет новая версия.
- По нажатию на кнопки начинает открываться опен офис :) Пусть открывается в эксель.

**Comment by panches** [comment]
Выполнил, версию не менял

**Comment by VsMoroz** [comment]
Закладка доступна только пользователям 5 уровня доступа.
Прошу сделать ее доступной и для 5 того и для 2 рого  уровней доступа.

**Comment by panches** [comment]
Выполнил, версию не менял

**Comment by VsMoroz** [comment]
Все супер. Большое спасибо !
