### ISSUE TITLE
Добавить поле Класс узла в закладку База ->Тех.площадки

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#118]
Привет ! 
Прошу добавить новоле поле Класс узла  между полями "№" и "Название" в закладке База ->Тех.площадки. 

Значение брать  из tblinform2.nclass_d которое ссылается на tab_nclass.id  наc интересует содержимое в   tab_nclass.name

**Comment by panches** [comment]
выполнил, v5.46.44
только tblinform2.nclass_d = tab_nclass.name.

**Comment by VsMoroz** [comment]
Ты прав, ну эт какой то непорядок, получается таблица tab_nclass.name для системы не нужна, нужна только как справка для людей.
Ну пусть пока будет так.
