### ISSUE TITLE
Добавить дату истечения гарантийного обязательства перед клиентом  для спутниковых модемов и передатчиков

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#119]
План:
1. Добавить два новых поля в таблицу в них  будет указываться крайняя дата по когда действует гарантия (модем и передатчик).
2. Добавить эти поля в интерфейс редактирования и добавления записей в закладку база ->  Клиент. Для спутникового интерфейса.
3. Определить значения по умолчанию для этих полей при добавлении новой записи в БД.
4. Модернизировать вью (появляется при двойном тапе на ТТ или на обьект) что бы  по истечению гарантии  дата и слова "не на гарантии" показывались красным.
5. Модернизировать функцию постановки наряда на выезд, что бы туда добавлялась  и информация о гарантийных обязательствах.
6. Получить от СЭ информацию о текущих обязательствах по гарантии и скриптом проставить для всего спутникового оборудования.
- детальнее распишу уже завтра.

**Comment by VsMoroz** [comment]
Прошу поменять название описания поля с "SN антены" на "SN модема" скриншот сейчас пришлю

**Comment by VsMoroz** [comment]
Добавим новые поля:
ALTER TABLE `net_equip` ADD `modem_warrant_end` DATE NOT NULL DEFAULT '0000-00-00' COMMENT 'Окончание гарантии модема' AFTER `s_n_DW` 

ALTER TABLE `net_equip` ADD `trans_warrant_end` DATE NOT NULL DEFAULT '0000-00-00' COMMENT 'Срок окончания гарантии приемопередатчика' AFTER `Line4` 

Прошу добавить эти поля в формы добавления/редактирования и отображения записей в спутниковом интерфейсе. С названиями "Модем гарантия до", "Передатчик гарантия до"
Помни что серйный номер передатчика и дата окончания гарантии передатчика есть только у Tooway   (да там нет пустого места в форме,  давай ее немного расширим)

**Comment by VsMoroz** [comment]
Новые поля не обязательны к заполнению, проверку не производим.

**Comment by panches** [comment]
выполнил, v5.46.45

**Comment by VsMoroz** [comment]
Спасибо, поля появились, отправил на тестирование, продолжим с пунтом 4.

4.Модернизировать вью (появляется при двойном тапе на ТТ или на обьект в закладке СУ) что бы по истечению гарантии дата и слова "не на гарантии" показывались красным.

Здесь нужна логика вот такая, анализ и действие нужно выполнить для каждого поля (modem_warrant_end  и trans_warrant_end) отдельно: 
- Если в  поле значение 0000-00-00 - ничего не делаем
- Если в поле значение >= now() добавить в окно отображение запись: Устройство гарантия до: дд.мм.гг или  Передатчик гарантия до: дд.мм.гг
- Если в поле значение < now() добавить в окно отображение запись : Устройство гарантия истекла: дд.мм.гг или  Передатчик гарантия истекла: дд.мм.гг  , где дд.мм.гг красным.

Пример сейчас пришлю в виде скриншота

**Comment by panches** [comment]
выполнил, v5.46.46

**Comment by VsMoroz** [comment]
Просьба внимательней, формат отображаемых данных нужен в виде:  дд.мм.гг

**Comment by panches** [comment]
исправил

**Comment by VsMoroz** [comment]
Прошу добавить возможность удалять информацию в полях со сроком окончания гарантии. Сейчас этого никак не сделать.

**Comment by panches** [comment]
добавил, версию не менял

**Comment by VsMoroz** [comment]
5.Модернизировать функцию постановки наряда на выезд, что бы туда добавлялась и информация о гарантийных обязательствах.

Прошу при постановке наряда на выезд для ТТ открытого на СУ, перед автоматом проверять если каждое поле, (modem_warrant_end и trans_warrant_end) отдельно:
    Если в поле значение 0000-00-00 - ничего не делаем
    Если в поле значение >= now() добавить в окно отображение запись: Устройство (s/n: net_equip.s_n_DW) гарантия до: дд.мм.гг  или Передатчик (s/n: net_equip.Line4) гарантия до: дд.мм.гг 
    Если в поле значение < now() добавить в окно отображение запись : Устройство (s/n: net_equip.s_n_DW) гарантия истекла: дд.мм.гг или Передатчик  (s/n: net_equip.Line4) гарантия истекла: дд.мм.гг 

**Пример:** 
"Само задание на выезд
Устройство (s/n: 4456223456) гарантия до: 15.12.16
Передатчик (s/n: EBR34W) гарантия до: 15.12.16 
Наряд на выполнение работ поставил: Януковский В.Ф. "

**Comment by VsMoroz** [comment]
Вот этот пункт делать не будем,  там условия таковы что прогнозная модель только навредит, какой будет срок гарантии  зависит только от приложения к договору и может варироваться в рамках одного дня.

3.Определить значения по умолчанию для этих полей при добавлении новой записи в БД.

**Comment by panches** [comment]
выполнил, v5.46.47

**Comment by VsMoroz** [comment]
Запустил апдейт, наблюдаем
