### ISSUE TITLE
Закладка Сервисы субпровайдера, некорректен отчет по кнопке "Экспорт в XLS"

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#120]
Привет !

Подконнекться к продуктивной базе попробуй сделать  "Экспорт в XLS" в экспорт должны попасть все записи которые на экране но туда как то попадают совсем не все.

Я нажал кнопку  Показать все затем импорт в эксель, вместо  ~ 3000  записей  - импортировалось  тольок 50

**Comment by panches** [comment]
Исправил, v5.46.46

**Comment by VsMoroz** [comment]
Спасибо !
