### ISSUE TITLE
Менять статус ТТ на "В работе", если я добавляю запись в ТТ и он находится в статусе "Пауза" и этот ТТ закреплен не за мной.

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#121]
Привет ! 
Прошу реализовать следующий функционал.
Проверяется при добавлении записи в ТТ пользователем, если пользователь добавляет ТТ не в ту закладку в которую он залогинился при запуске программы (тоесть в чужой ТТ) и если тт находится в статусе "Пауза" (trubl.status_tt = 3 или 4) то переводить его в статус "В работе" (trubl.status_tt = 2)

**Comment by panches** [comment]
Привет!
Выполнил, v5.46.49

**Comment by VsMoroz** [comment]
Спасибо работает
