### ISSUE TITLE
Возможность создавать новую запись на основании существующей, сервисы субпровайдеров

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#122]
Привет ! 
Сейчас идет проект по внедрению многих каналов для одного заказчика и там очень много задач похожих друг на зруга только отличается адрес точки Б пользователи просят добавить фнукционал: 

По правому щелчку мыши  на записи в закладке Сервисы субпровайдера выбрать в меню, "Добавить запись  копию" при щелчке на нее открывается форма Добавления новой записи с скопированными в форму данными из той записи на которой щелкали правой кнопкой мыши. 

Дальше они поменяют что им нужно и нажмут сохранить. Эта запись сохранится как новая.

**Comment by panches** [comment]
Выполнил, v5.46.54

**Comment by VsMoroz** [comment]
Пользователи просят при создании копии не заполнять поля выделенные красным и желтым (пришлю в почту), а именно:
- Название
- Дата включения
- Дата подачи услуги клиенту
- № канала
- Доп.договор
- Статус
- Ид в планере
- Дата постановки задачи
- Дата отключения
- Налоговая накладная
- Акт.вып.работ
- Номер счета
  -Примечание

**Comment by VsMoroz** [comment]
Прошу добавить кнопку очистки полей "Подвязать" на картинке выделенно фиолетовым в форму создания новой записи в закладку ССУ

**Comment by panches** [comment]
Ввполнил. v5.46.56

**Comment by VsMoroz** [comment]
Спасибо ! работает нормально.
