### ISSUE TITLE
Поиск городов сделать поиском а не выбором из списка, закладка сервисы субпровайдеров

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#123]
Привет ! 
Модернизация полей Город А и Город Б - в формах добавления и редактирования записей в закладке  сервисы субпровайдера.

Сейчас поля выглядят как выпадающий список. Прошу переделать их в такую же форму ввода как у поля "Оператор", тоесть что бы город можно было искать через поисковую форму.

Сейчас многие города переименовываются  законом о декомунизации - пользователям сложно их найти в выпадающем списке т.к. новые названия становятся первыми а старые сзади в скобках

**Comment by panches** [comment]
в версии 6.0 уже сделано.

**Comment by VsMoroz** [comment]
6.0 мы не можем выпускать в производство без основательного тестирования. Уже пользователей системы для которых она один из основных рабочих инструментов - много

**Comment by panches** [comment]
Выполнил, v5.46.54

**Comment by VsMoroz** [comment]
Спасибо все хорошо
