### ISSUE TITLE
Исчезает символ "\" в форме добавления и редактирования записи в СК

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#125]
Прошу модернизировать логику, сейчас при добавлении новой записи или радактировании в СК (наверное во всех полях) но точно  в полях "Техническая схема ПМ" и "Примечание" спецсимвол \ удаляется. Давай его просто экранируем.

**Comment by panches** [comment]
выполнил, v5.46.59

**Comment by VsMoroz** [comment]
Работает, закрываю ишью
