### ISSUE TITLE
Отключить проверку на выбранную зону ответственности при нажатии кнопки "Создать ТТ для записи"

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#126]
Привет ! 
Прошу отключить проверку (она срабатывает если выбрать зону ответственности  "Все Все"  и нажать "Создать ТТ для записи", появится окно " определите зону ответственности" )

Описанная выше проверка не нужна т.к. дублирует проверку на зону ответственности в форме создания ТТ.

**Comment by panches** [comment]
выполнил, v5.46.59
p.s. в options исправления сделал

**Comment by VsMoroz** [comment]
Спасибо работает.
