### ISSUE TITLE
Доработкии вокруг доп договоров в учете ССУ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#127]
**Сложность**: пользователь не может отличить записи ССУ у которых доп договора нет(и не будет)  и  ССУ у которой доп договор забыли внести. Сейчас в обоих случаях пользователь видит просто пустое поле.
**Решение**:  при создании Договора с субпровайдером, будем автоматом для него создавать  доп договор с названием "нет доп.договора" и все. Все остальное пользователи будут делать сами.

**Comment by VsMoroz** [comment]
Для уже существующих договоров, я создам отдельным запросом  записи "нет доп.договора"

**Comment by panches** [comment]
выполнил, v5.46.61

**Comment by VsMoroz** [comment]
Все работает, закрываю
