### ISSUE TITLE
Подсказывать пользователю что нужно изменить статус ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#128]
Привет ! 
Прошу модернизировать логику добавления записи в ТТ.
После нажатия на кнопку "добавить запись в ТТ" и добавления записи в ТТ, выполнить проверку какой статус ТТ:
- если ТТ находится в зоне ответственности в которую залогинился сотрудник и статус ТТ  trubl.status_tt = 1  -> Вывести сотруднику небольшое окно с фразой: "Добавлена запись в ТТ со статусом (SELECT forIngener  FROM tab_status_tt WHERE id = 1), хотите перевести ТТ в статус (SELECT forIngener  FROM tab_status_tt WHERE id = 2) ?
  И две кнопки, Да и Отмена, при  нажатии кнопки да, изменить trubl.status_tt = 2
- если статус ТТ любой другой - ничего не делать.

**Comment by panches** [comment]
Выполнил, v5.46.63

**Comment by VsMoroz** [comment]
Спасибо, пока закрываю

**Comment by VsMoroz** [comment]
Поменяй названия кнопок с yes no на Да, Отмена (как в исходном тех.задании)

**Comment by VsMoroz** [comment]
Во всплывающем окне прошу сделать что бы надпись была  в две строки: (так визуально читается легче)

**Пример:**
Добавлена запись в ТТ со статусом "Ожидание".
    Хотите перевести ТТ в статус "В работе" ?

**Comment by panches** [comment]
Выполнил, v5.46.64

**Comment by VsMoroz** [comment]
Приветствую, прошу при создании ТТ в закладке "Плановые" создавать его сразу со статусом " В работе"  trubl.status_tt ='2'

**Comment by panches** [comment]
Сделано, v5.46.65

**Comment by VsMoroz** [comment]
Спасибо, закрываю

**Comment by VsMoroz** [comment]
Программа вновь и вновь требует сменить статус ТТ с "ожидания" в "в работе" хотя после первого вопроса о изменении пользователь согласился и изменение в БД произошло и статус тт уже в работе

Как повторить: взять любой ТТ в ваше зоне ответственности в статусе  "ожидание" добавить в него запись (программа спросит хочешь ли сменить статус - согласиться), сразу же ввести еще одну запись в этот же ТТ увидеть что программа опять спрашивает разрешение на смену статуса (но статус уже сменен при первой записи в ТТ)

**Comment by panches** [comment]
исправил, версию не менял

**Comment by VsMoroz** [comment]
Ура !
