### ISSUE TITLE
Добавление записи в подчиненный ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#129]
Сейчас при попытке добавить запись в подчиненный ТТ, сразу после нажатия кнопки "Добавить запись"    в окне активных ТТ пропадают подчиненные  ТТ и появляются неподчиненные.

Прошу модернизировать логику работы интерфейса, что бы при добавлении ТТ в подчиненный ТТ он не ичезал, а оставался на месте и в него или другой подчиненный этому же материнскому, можно было добавить еще запись.

**Comment by panches** [comment]
выполнил, v5.46.66

**Comment by VsMoroz** [comment]
Сейчас при добавлении записи в подчиненный ТТ, сразу после добавления куда то пропадают русские названия столбцов и появляются английские названия, а так же ширина столбцов резко меняется на непрогнозируемые величины **и меняется очередность столбцов** (поле дата открытия ТТ смещается на один столбец влево). Пришлю картинку письмом
Прошу продолжить модернизацию, после добавления записи в подчиненный ТТ, названия полей их ширина и очередность не должны меняться

**Comment by panches** [comment]
исправил, версию не менял

**Comment by VsMoroz** [comment]
> и меняется очередность столбцов (поле дата открытия ТТ смещается на один столбец влево).
> этот баг по прежнему присутствует

**Comment by VsMoroz** [comment]
При чем смещение поля Дата создания ТТ проявляется сразу как только нажимаешь кнопку показать подчиненные ТТ

**Comment by VsMoroz** [comment]
Так же сразу после старта программы поле "Дата открытия ТТ" смещается влево и размещается между "Клиент" и  "Причина открытия"  вместо того что бы находится в том месте в которое я его разместил перед закрытием программы.

**Comment by panches** [comment]
В закладке "Активные" поля при запуске расположены ...., "Клиент","Открыт","Причина",... и при выборе "Всех подчиненных", "Подчиненных к ТТ" порядок не меняют. v5.46.67

**Comment by VsMoroz** [comment]
Попробуй разместить поля так как это у 98% пользователей : ТТ, S,pri,SLA, Клиент, Причина открытия,Статус, Открыт, Ответственный, Открыл. 
Перезапусти программу, очередность полей не изменилась ? 

После того как это будет исправлено, снова размести поля в очередности как в начале сообщения и попробуй добавить запись в подчиненный ТТ, очередность полей сохранилась ?

**Comment by panches** [comment]
исправил, версию не менял

**Comment by VsMoroz** [comment]
Спасибо

**Comment by VsMoroz** [comment]
Поговорил с пользователями, ты был прав, прошу переместить поле  "Открыт" между полями "Клиент"  и "Причина открытия"  что бы так было и при работе с не подчиненными ТТ и с подчиненными тоже.

**Comment by panches** [comment]
исправил, v5.46.68

**Comment by VsMoroz** [comment]
Спасибо, все хорошо
