### ISSUE TITLE
Прогнозировать срок устранения аварии при добавлении официальной версии аварии

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#130]
Привет ! 
По следам #88 и #108  прошу модернизирвать логику добавления оф.причины аварии в ТТ открытые на **СК** (акцент на СК - это важно):
Интерфейс добавления записи в ТТ, когда пользователь в ТТ впервые  выбирает предварительную причину, (тоесть когда он выбрал поле подкатегории аварии) нам становится известно то что будет добавлено в поле trubl.type_2_d   нужно выполнить рассчет срока устранения аварии используя вот этот запрос: febc13a0ea3351442f4ab87750047f2813aee311, получить срок устранения в часах после создания ТТ, ОБРАБОТАТЬ и подставить в интерфейсе в поле "Срок устранения"

Под обработать имеется ввиду следующее: нужно проверить если запрос выдаст ничего или null или 0 или значение больше чем в SLA на СК -  тогда ничего не делать. 

Возьмись за задачу в рабочем порядке, после выполнения текущих задач.
Маякни мне в скайп перед тем как начинать, я голосом проговорю особенности написанные выше еще раз..

**Comment by panches** [comment]
выполнил, v5.46.67

**Comment by VsMoroz** [comment]
работает , спасибо
