### ISSUE TITLE
Созданием нового шаблона email оповещения (CrAGRCL) силами серверной части

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#131]
Прошу создать новый шаблон email оповещения (как мы это делали ранее #102 ).
**Название:** CrAGRCL

Нужно взять за основу профиль UGBK и в шаблон close добавить в него  причину аварии как в шаблоне BASE, пример:

Было:
TT: #380 840 - Close 
03.11.16 11:02 (UTC+2)
-------

После модернизации:
TT: #380 840 - Close 
03.11.16 11:02 (UTC+2)
Причина: авария у пользователя
-------

**Comment by panches** [comment]
v1.9.27, выложил

**Comment by VsMoroz** [comment]
Добавь CrAGRCL в выпадающем списке в каталоге партнеров в приложении клиентдб

**Comment by panches** [comment]
Сделано, v5.46.65

**Comment by VsMoroz** [comment]
Работает спасибо

**Comment by VsMoroz** [comment]
Просят в шаблон вставить два диеза  и двоеточие перед словом "Причина"

После модернизации:
TT: #380 840 - Close
03.11.16 11:02 (UTC+2)
##: Причина: авария у пользователя

**Comment by panches** [comment]
вставил два диеза, версию не менял

**Comment by VsMoroz** [comment]
Спасибо !

**Comment by VsMoroz** [comment]
Пользователь прислал пожелания по модернизации:
Прошу модернизировать  шаблон для процесса close  :

TT: #382 668 - Close 
15.11.16 12:28 (UTC+2)

##  [эту строчку переместить ниже вместо строчки помеченной к удалению] ##: Причина: авария на телекоммуникационной сети

Open TT
15.11.16 12:26

[эту строчку удалить] ##: Отсутствует связь super@ms.com  Tue, 15 Nov 2016 12:26:30 +0200

###: Хороший банк, передача данных, 5 Мбит/с, (Город, ул. Гринченка - Город, ул. Кирова)

## CID: D262148

`

**Comment by panches** [comment]
модернизировал, версию не менял

**Comment by VsMoroz** [comment]
Работает спасибо
