### ISSUE TITLE
Апдейтить состояние просмотрено/не просмотрено ТТ при добавлении записи в подчиненный ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#132]
Привет  ! 
Прошу модернизировать логику при добавлении записи в ТТ:

Мы сейчас смотрим, если этот ТТ не находится в зоне ответственности того кто добавляет комментарий - тогда апдейтим состояние ТТ как непросмотренный (что бы инженер знал что там что то изменилось)

Прошу добавить еще одну проверку: при добавлении записи в ТТ, посмотреть нет ли у него материнского ТТ, если есть проверить если этот ТТ находится в чужой зоне ответственности (для добавляемого) тогда сделать этот материнский непрочитанным.

Почему нельзя совместить эти две проверки в одну, потому что у нас бывают  случаи когда подчиненный и материнский ТТ лежат в разных зонах ответственности, поэтому  проверки должны быть двумя независимыми следующими одна за другой.

Спасибо

**Comment by panches** [comment]
выполнил, v5.46.66

**Comment by VsMoroz** [comment]
Спасибо работает
