### ISSUE TITLE
Добавить # в окно всплывающее при двойном тапе на ТТ открытый на СК, ОК, СУ, СС

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#133]
При двойном тапе на ТТ открывается окно просмотра где есть номер ТТ, прошу перед номером ТТ вставить символ # , а после номера ТТ убрать запятую  и так же убрать знак №

**Пример как сейчас:** 
ТТ№: 382227, Причина открытия: Не работают номера телефонные, nikolay@ms.com  Fri, 11 Nov 2016 15:53:00 +0200, по обращению клиента
CID: D9999997, SLA: Стандарт (std), срок устранения: 24 ч., первый контакт через: 2 ч.

**Пример после модернизации:**
ТТ: #382227  Причина открытия: Не работают номера телефонные, nikolay@ms.com  Fri, 11 Nov 2016 15:53:00 +0200, по обращению клиента
CID: D9999997, SLA: Стандарт (std), срок устранения: 24 ч., первый контакт в течении: 2 ч.

**Comment by panches** [comment]
выполнил, v5.46.67

**Comment by VsMoroz** [comment]
Спасибо
