### ISSUE TITLE
Введение в систему понятия сегмент рынка (розница, корп, опт, смб)

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#134]
Введение в систему понятия сегмент рынка (розница, корп, опт, смб)
Просто возле каждого менеджера проставим к какому сегменту рынка он относиться.

Добавим новое поле:  **tab_access.type_business**, int(2), по умолчанию 5, Тип рынка, из tab_catal_comm_dep.id

Добавим в каталог партнеров это поле

Добавим это поле  в отчет Статистика -> Статистика SLA

**Comment by panches** [comment]
Уточнение:
"Каталог партнеров": добавить в отображении таблицы после поля "Менеджер"?
"Статистика СЛА": куда здесь добавлять, в отчетах поля "Менеджер" нет?

**Comment by VsMoroz** [comment]
Модернизирую тех задание:
В каждом клиенте будем указывать к какому типу бизнеса он относится.
Добавим новое поле в БД: 
ALTER TABLE  `tab_klients` ADD  `type_business` INT( 2 ) NOT NULL DEFAULT  '5' COMMENT  'Тип рынка, из tab_catal_comm_dep.id'
В каталог партнеров, в формы отображения/добавления/редактирования прошу добавить тип бизнеса (по умолчанию = 5, Прочее) в форме редактирования и добавления это поле должно быть в виде выпадающего списка со значениями из tab_catal_comm_dep.namedepartment

**Comment by VsMoroz** [comment]
Прошу добавить поле "Тип бизнеса" в три отчета Статистика -> Статистика SLA строящиеся по нажатию кнопок "Детальнее"
3cc7bc1e70e4e2017c56433011563991b3bd1456 глянь на изменения

**Comment by panches** [comment]
выполнил, v5.46.68

**Comment by VsMoroz** [comment]
Прошу модернизировать запросы  в этой статистике что бы отсеять  технические записи и старый формат данных и розницу
Изменения вот здесь, касаются строки количества услуг с выбранным СЛА, а так же ее деталиция.
8304751ae6218f5280f8a432dc6d892c76d89262

**Comment by panches** [comment]
выполнил, v5.46.69

**Comment by VsMoroz** [comment]
Перенесено во внутреннюю систему
