### ISSUE TITLE
Сереверная часть: Изменить шаблон письма при отправке email уведомления только при открытии ТТ, убрать строчку с датой временем открытия

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#48]
Привет ! 

Серверная часть, убери в шаблоне письма извещения о открытии ТТ  дату время открытия(только о открытии!!, шаблоны о апдейтах и закрытии, не трогай)

10.06.15 09:25 (UTC+3)

**Comment by panches** [comment]
выполнил, v1.9.9

**Comment by VsMoroz** [comment]
Работает нормально, спасибо !
