### ISSUE TITLE
Не показывает весь список договоров (закладка Сервисы субпровайдера) при редактировании записи

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#49]
Не показывает весь список договоров (закладка Сервисы субпровайдера) при редактировании записи, в поле "Договор" в выпадающем списке видно только один договор. А должны быть видны в выпадающем списке все договора с этим партнером.

Если нажать рядом кнопку +  а затем во всплывшем меню  - отмена, то вот тогда в списке поля Договор появляется весь список договоров с этим партнером.

Я так понял сюда картинки никак не добавить?  Только в виде ссылки..

**Comment by panches** [comment]
исправил, v5.45.28

p.s. про картинки не понял, разжуй пожалуйста.

**Comment by VsMoroz** [comment]
В гугле можно было прикладывать файл к сообщению, здесь вроде нет. Завтра протестирую изменения, отпишусь.

**Comment by VsMoroz** [comment]
Работает, спасибо

**Comment by panches** [comment]
Редактирование ССу: Перенес отображение Договора и Доп.договора в конец процедуры. V5.45.35
