### ISSUE TITLE
Добавить проверку на дубляж при привязке ТТ к объекту у  которого уже есть открытый ТТ.

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#50]
Привет !
При создании ТТ у нас есть модуль, который проверяет, нет ли объекта на который открывается новый ТТ,  уже открытого ТТ, если есть выводит инженеру предупреждение:
"ТТ для данного сервиса уже создан. Хотите создать плановый ТТ ?" и прадлагает выбор ДА или НЕТ.

Давай этот модуль чуть модернизируем и  повесим на процедуру привязки ТТ (созданного роботом имеющего     inv_num_kli=0 и tab_on=7) к объекту.

Пусть он выводит информацию (без возможности выбора)   о том что  "Данный сервис уже имеет открытый ТТ номер такой то"

**Comment by VsMoroz** [comment]
И не позволяет привящаться к такому сервису.

**Comment by panches** [comment]
Выполнил, v5.45.29

**Comment by VsMoroz** [comment]
Функция хорошая, позволяет избежать ситуации когда два сотрудника паралельно работают над одной и той же аварией.
Необходима модернизация информации которая отображается во всплывающем окошке при попытке подвязать ТТ  к объекту у которого уже есть ТТ:

**Формат сообщения:**
Сервис уже имеет открытый ТТ #номерТТ  дата открытия(trubl.date_of_start)  заКемЗакреплен(trubl.user_id)
Подчинен TT #413000 22.06.14 Ткач О

**Пример ТТ подчинен:**
Сервис уже имеет открытый ТТ #413545  23.06.14 Гашенко В
Подчинен TT #413000 22.06.14 Ткач О

**Пример  ТТ не подчинен 2:**
Сервис уже имеет открытый ТТ #413545  23.06.14 Гашенко В

**Comment by panches** [comment]
Выполнил, v5.45.34

**Comment by VsMoroz** [comment]
Спасибо ! Пока закрываю, вернемся к этому вопросу попозже еще раз, когда ответственный выработает алгоритм для инженера. Там будет еще одна маленькая автоматизация.

**Comment by VsMoroz** [comment]
Вернемся к этому вопросу, в процессе эксплуатации выявились необходимые модернизации:

Сейчас мы запрещаем привязывать ТТ к обьекту если у этого объекта уже есть открытый ТТ ( не важно какой плановый или профилактический что не хорошо :) )
Давай изменим критерий: Будем запрещать привязывать ТТ к обьекту только если этот объект имееет открытый ТТ по сигналу НМС или по обращению клиента и имеет статус А или П
( trubl.date_of_end = '0000-00-00' ; trubl.type_trubl_d = 2 или 3 ; trubl.state_tt = 0 или 1 ;)

**Comment by panches** [comment]
Выполнил, v5.45.47, файл выложил
