### ISSUE TITLE
Добавить кнопку "Назначить ответстсвенного" и "Перейти к объекту" в закладке  "Поиск ТТ" для пользователей уровня 2 и 5

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#51]
Добавь плиз кнопку "Назначить ответстсвенного" в закладку  "Поиск ТТ" для пользователей уровня 0,2,5.
Функционал у кнопки такой же как у одноименной кнопки в закладке Trouble Tickets - Активные

А так же кнопку "Перейти к объекту", для пользователей такого же уровня доступа, действует она по аналогии правого щелчка на ТТ и выборе меню "Перейти к объекту",

**Comment by panches** [comment]
Выполнил, v5.45.30

**Comment by VsMoroz** [comment]
Кнопке "вывести из отложенных" смени название на  "Из отложенных" и добавь иконку со стрелочкой - что бы она полностью соответствовала такой же кнопке  в закладке Trouble Tickets -> отложенные

**Comment by panches** [comment]
Выполнил

**Comment by VsMoroz** [comment]
Спасибо все хорошо !
