### ISSUE TITLE
Добавить поле "Ответственный" в закладку "Поиск ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#52]
Привет ! 
Добавь поле "Ответственный"  (полностью аналогиное такому же полю из "Активные ТТ") в закладку "Поиск ТТ" разместив его между полями time_of_end и description

**Comment by panches** [comment]
Выполнил, v5.45.31

**Comment by VsMoroz** [comment]
Спасибо ! 
Прицепом поменяй подписи полей в закладке "Поиск ТТ"  с технических на презентабельные, подпиши их так же как в закладке Активные ТТ

**Comment by panches** [comment]
Выполнил

**Comment by VsMoroz** [comment]
Спасибо ! Все нормально.
