### ISSUE TITLE
Экранировать кавычки при создании Договора в каталоге Договоров

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#53]
Каталог договоров: Справочники -> Договора ССу
При попытке добавить договор для пратнера у которого в имени присутствуют " - вываливается ошибка синтаксиса.
- Пример был в сегодняшней переписке

**Comment by panches** [comment]
Выполнил, v5.45.32

**Comment by VsMoroz** [comment]
Спасибо
