### ISSUE TITLE
Импорт задач из планера в БДСЭ через message broker

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#54]
Начнем ?
Задание вот по этой ссылке 
https://github.com/VsMoroz/tt-system-data/tree/development/RabbitMQ

**Comment by VsMoroz** [comment]
Ты смотрел, библиотеку для php.
А так же  смотрел можно ли запустить постоянно работающий сам по себе сервис на php ?

**Comment by panches** [comment]
Библиотека: https://github.com/videlalvaro/php-amqplib
Как запустить сервис пока не разобрался.

**Comment by VsMoroz** [comment]
По поводу  php и фонового процесса, мы не первые ;)

https://www.google.com.ua/search?q=php+%D1%84%D0%BE%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81&client=opera&oe=utf-8&channel=suggest&gws_rd=ssl&oq=php+%D1%84%D0%BE%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81&gs_l=heirloom-serp.3...14696.18667.0.18667.8.7.0.0.0.0.0.0..0.0....0...1ac.1.34.heirloom-serp..8.0.0.AVqMNxQ6su4

**Comment by panches** [comment]
Это можно сделать через JS+Ajax.
Появилась другая проблема: я вошел в ступор с RabbitMQ-клиентом на PHP.

**Comment by panches** [comment]
Разобрался. Мне надо для тестов пример json сообщения, котрое будет присылаться. 
Структура таблиц(поля, типы) и что какое поле означает в нашей структуре.

**Comment by VsMoroz** [comment]
Отправил  по  email пример json

**Comment by panches** [comment]
Запишу для памяти: есть притензии к данным. 
При декодировании json в object обнаружил проблему в данных:
1) если в тексте встречается '\', то декодировать не получается. Необходимо менять на '/'.
2) строковые данные передаются в двойных кавычках ("), если внутри есть еще одни ", то декодировать не получается. 
Эти проблемы необходимо устранять на этапе формирования json-файла.

**Comment by panches** [comment]
Уточенение:
Одна \ проходит, две \ - нет
Не проходит / вообще
Кавычка (') не проходит

**Comment by VsMoroz** [comment]
Привет, похоже все неудобные символы (" и \) как и  в случае с mysql экранируются  символом  \
Это стандартный подход. Вот  в PHP тоже так http://php.net/manual/ru/regexp.reference.escape.php

**Comment by VsMoroz** [comment]
И вот тоже описывают что все должно быть нормально, пришли мне кусок кода, попробуем вдвоем посмотреть (можно почтой)

http://php.net/manual/ru/language.types.string.php#language.types.string.syntax.double

**Comment by VsMoroz** [comment]
Json валидный, можно проверять вот здесь: http://jsonlint.com/

Эта ошибка это заморочки php как  его регулярные выражения обрабатывают строки,.
Что бы заработало - достаточно добавить еще одну \ (если в json приехало \\ то найти это сочетание и добавить косую что бы стало так \\\) тогда нормально импортируется.

Вот здесь об этом упоминается:
http://php.net/manual/ru/regexp.reference.escape.php

**Comment by panches** [comment]
Да, это работает. Но:
- если руками в файле сделать изменения, то работает;
- програмно сделать это не получается, PHP ругается.

Например,
Есть функция str_replace(что найти, на что поменять,  строка источник изменений), то
$str = str_replace('\\','\\\',$str); выдаст ошибку. 

Вывод: перед отправкой данных на сервер RabbitMQ, эти данные нужно проверять функцией 
$obj = json_decode($msg_body). Если $obj != NULL - смело отсылается.

**Comment by VsMoroz** [comment]
С той стороны данные готовятся на  C  у него  наверное таких функций нет как и сложностей с  экранированным \.

Хм... как бы нам так сделать что бы и php смог распознавать  Json и не терять приемственности  (тоесть оставить json в формате который будет понятен любой системе).

Думаю !

**Comment by panches** [comment]
Еще мысли: все эти спецсимволы (\r,\n и т.д.) лишние (мусор), их в тексте не должно быть.

**Comment by VsMoroz** [comment]
Ты что!  Это же данные пользователей, к ним нужно относиться бережно, они ранимые как дети, чуть что не так и перестают размножаться, загубишь цивилизацию ;)

**Comment by VsMoroz** [comment]
Привет ! 
После встречи с Димой, удалось получить данные из rabbitMQ  методом исключения VHOST  из параметров при создании обьекта. Давай будем модернизировать код, подтягивать все задачи циклом и  парсить json, сохранять данные в БД.

**Comment by panches** [comment]
Файл, который принимает данные и записывает в БД выслал на почту.

**Comment by VsMoroz** [comment]
Саня брось мне повторно файлик, не могу найти чето. Куда то переложил видать.

**Comment by panches** [comment]
https://github.com/VsMoroz/tt-system-data/tree/development/RabbitMQ

**Comment by VsMoroz** [comment]
Закрыта за неактуальностью
