### ISSUE TITLE
Статусы ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#55]
План: 
- ввести в систему статусы ТТ в явном виде которые будут переключаться в ручном режиме;
- навесить на статусы автоматические переходы в тех случаях когда они возможны
- навестить на изменение статусов  логику (автоматизировать работу с учетом работы первой линии)

*Не забыть укр - english языки

Статусы для  клиента : 
1. В ожидании
2. В работе
3. Авария у пользователя
4. Решено

Статусы для пользователя системой:
1. В ожидании
2. В работе
3. Пауза: (ожидаем  действия со стороны  других подразделений компании, выезда группы или от партнеров)
4. Пауза: авария у пользователя
5. Решено

**Comment by VsMoroz** [comment]
Поработаем над эти ? :)

**Comment by panches** [comment]
Давай поработаем.

**Comment by VsMoroz** [comment]
Добавил файлик со статусами tt-system-data/TT-engine/Статус ТТ/tab_status_tt.sql

**Comment by VsMoroz** [comment]
Описал изменения в интерфейсе (глянь мои последние два коммита)
https://github.com/VsMoroz/tt-system-data/commit/5cbd2784e4d30a27d61a404c5a39fe12de8cd168
https://github.com/VsMoroz/tt-system-data/commit/72da7831049e11f83b9544ad5236fe7c36a75ea2

**Comment by panches** [comment]
Приступаю. Задержка будет за выпадающим списком, теоретически я об этом читал, а практически ...

**Comment by VsMoroz** [comment]
Ок, давай тогда пока сделаем промежуточный вариант, что бы в Активных ТТ просто отображался статус. А при добавлении записей в ТТ - его можно было поменять.

**Comment by VsMoroz** [comment]
Описание фильтра статусов и принятых изменений в интерфейсе описывающих "как пользователь сможет менять статус ТТ" https://github.com/VsMoroz/tt-system-data/commit/a3fa648ce3c2443a00de334fa9823aa9206f4003

**Comment by panches** [comment]
Столкнулся с серьезной проблемой, что б добавить новое поле прийдется все поломать в закладке АКТИВНЫЕ. MySQL компонент в Delphi 7 отказывается работать как положено. Обойти проблему можно, но нужно время для переделывания всех запросов.

**Comment by panches** [comment]
Выполнил, v5.45.41. Файл выложил.

**Comment by VsMoroz** [comment]
Ты ж в инсталляционном пакете поставь хост и хостбек такие как у нас (такие какие были в предыдущей версии)

Отцентрируй поле "Открыт" и "Открыл" по правой стороне

В поле "Открыт" сделай значение года коротким, не .2015 а .15

А так же давай сделаем что бы ширина полей в закладке Активные тоже запоминалась, а то сразу оно некрасиво получается,  я расставляю нужную ширину, после перезапуска клиента все слетает и снова нужно расставлять, а так в целом ничего ! 

Фильтрация по статусу ТТ - слетает как только я выбираю любую другую зону ответственности, а так же при добавлении записи в любой ТТ. Нужно что бы она не слетала а была всегда.
- А вообще я сейчас щелкаю и примеряю на себя насколько практично и чувствую что это маленькое изменение даст мощный эффект в организации работы, очень хорошая штука !

**Comment by panches** [comment]
Исправил, v5.45.42.  Файл выложил.

**Comment by VsMoroz** [comment]
При запуске в окне фильтра по статусам- пишет edit4 :)
Можно сделать так что бы при загрузке фильтр уже содержал галочки того что он отображает. А то сейчас получается при перезапуске приложения галочки в фильтре не стоят (хотя фильтр нормально работает)

Поле "Открыл" давай вернем центрование к левому краю.

При правом щелчке на ТТ открывается меню, давай в нем заменим надпись: "Изменить статус ТТ .." на "Изменить (А П У) влияние на сервис"  а то две строчки со словом Статус будут путать сотрудников

**Comment by panches** [comment]
Выполнил, v5.45.43. Файл выложил.

**Comment by VsMoroz** [comment]
Добавление функционала: a6c0d81a28f4847994f6e5403c35529a170093f6 Когда инженер выбирает статус Пауза, появляется окно в котором  можно выбрать до какого времени устанавливается пауза (по уполчанию через 4 часа с момента изменения статуса), а так же по желанию можно добавить причину ожидания. После истечения этого срока статус ТТ вернется к "В работе"

**Comment by VsMoroz** [comment]
Обрати внимание, в версии 5.45.43 при изменении статуса для одного ТТ, отображение в активных ТТ теряет значение выбранных мной статусов и начинает отображать все ТТ со всеми статусы и вообще без статусов тоже.

**Comment by VsMoroz** [comment]
Так же просьба модернизировать модуль системы ТТ который выполняется при ее запуске, что бы он анализировал если в   сохраненном файле нет информации о том какие фильтры пользователь выбрал ранее, то добавить информацию с вывбранными по уполчанию фильтрами "В ожидании", "В работе", "Решено"

**Comment by panches** [comment]
Выполнил все дополнения и пожелания, v5.45.44 и v1.9.11. Файлы выложил.

**Comment by VsMoroz** [comment]
Вот эта проблема осталась: 

при изменении статуса для одного ТТ, отображение в активных ТТ теряет значение выбранных мной статусов и начинает отображать все ТТ со всеми статусы и вообще без статусов тоже.

**Comment by panches** [comment]
Это исправил. Было обновление по кнопке "выбор зоны ответственности" заменил на "Фильтрацию по статусу ТТ"

**Comment by VsMoroz** [comment]
При выборе статус "Пауза" (не важно пауза партнеры или пауза клиент),  что бы в всплывающей форме фокус был сразу на кнопке "Отложить" Что бы сотрудник выбрал статус и нажал ентер и статус сразу поменялся.

Название формы измени с отложить на название статуса.
Название кнопки отложить изменить на " установить статус"

**Comment by VsMoroz** [comment]
Записи вносимые в ТТ при изменении статуса должны быть от "автомат" Контактировал с - должен содержать в себе фио кто меняет статус"

В таком случае эти технические изменения не будут видны инженеру в обычном режиме

**Comment by panches** [comment]
Исправил, Файлы выложил.

**Comment by VsMoroz** [comment]
Тестирую, 

В добавляемой в ТТ записи убери слово "Причина:", так будет лаконично:

Пауза, партнеры, До : 13:54:09 2015-08-31, **Причина:**  Ожидаем инфо от выездной группы

**Comment by VsMoroz** [comment]
И давай сделаемв добавляемых записях в поле дескрипшин -  дату в нашем формате и уберем секунды:

Пауза, партнеры, До : **13:54 31.08.15**, Причина: Ожидаем инфо от выездной группы

**Comment by VsMoroz** [comment]
Так же прошу поменять местами в закладке активные ТТ (именно ТТ)  поля "Открыл" и "Ответственный"

**Comment by panches** [comment]
Исправил, Файл выложил.

**Comment by VsMoroz** [comment]
Можно сделать что бы  при обновлении версии, все пользовательские настройки (ширина полей, выбранные фильтры в поле статус) не слетали ?

**Comment by panches** [comment]
Сделал: настройки сохраняются в отдельном файле, который создается автоматически и в комплекте установочных файлов не идет. Настроиш один раз и устанавливай новые версии в ту же папку. Файл выложил.

**Comment by VsMoroz** [comment]
При нажатии кнопки "закрыть ТТ" выдает такую ошибку - Field 'klient_calc' not found

**Comment by panches** [comment]
Исправил. Файл выложил.

**Comment by VsMoroz** [comment]
Вопрос, сможем сделать выделениие только поля статус цветом,  в зависимости от статуса ?

**Comment by VsMoroz** [comment]
Пытаюсь назначить ТТ сотруднику , получаю ошибку: "Field in_num not found" ТТ назнасается но запись в ТТ о том что он назначен - не вносится

**Comment by panches** [comment]
Какими цветами надо выделять?

**Comment by VsMoroz** [comment]
Вопрос, сможем сделать выделениие только поля статус цветом,  в зависимости от статуса ? 
Я предлагаю так: каждому статусу (именно шрифту текста и только в  поле статус) назначить свой цвет по такой системе:
Шестнадцатиричное вычисление: 
берем число 0x095110+ tab_status_tt.id умножить на 0x186A0 = результат вставить в поле цвета

**Comment by panches** [comment]
Ошибку исправил, цвета добавил. v5.45.45. Файл выложил.

**Comment by VsMoroz** [comment]
Можешь сделать версию, где будет цвет статуса будет меняться не фоном, а цветом шрифта в этом поле ? Надо понять какой лутчше

**Comment by panches** [comment]
Сделал. Файл выложил.

**Comment by VsMoroz** [comment]
Такая цветовая раскраска супер ! 
Принимаем ее за основу.

**Comment by panches** [comment]
Вижу, а иногда вижу так: ( обл.)

**Comment by VsMoroz** [comment]
Интересный эффект наблюдаем, берем ТТ  который раньше откладывался но сейчас вернулся из отложенных:

Нажимем ему "Пауза партнеры"  через пару минут от нештатно возвращается в работу.
Пытаемся его отложить - он опять через пару минут нештатно вылазит из отложенных,
Вот листинг из ТТ:

31.08.2015 16:51:29
Отложено
До : 8:15:55 2015-09-02, Причина: До инфо от Лесняка
Николай

02.09.2015  8:16:17
-
перенесено из отложенных: Николай.
автомат

02.09.2015  16:45:36
Николай
Пауза, партнеры, До : 08:15 14.09.15, До инфо от Лесняка
автомат

*\* ТТ вернулся в статус "В работе"**

02.09.2015  16:46:43
Николай
Пауза, партнеры, До : 08:15 14.09.15, До инфо от Лесняка
автомат

*\* ТТ вернулся в статус "В работе"**

02.09.2015  16:52:10
Отложено
До : 08:15 14.09.15, Причина: До инфо от Лесняка
Николай

02.09.2015  16:56:17
-
перенесено из отложенных: Николай.
автомат

**Comment by panches** [comment]
Надо добавить поля в trubl время и дату для пауз отдельно. Совместно с отложенными работа не получается.

**Comment by VsMoroz** [comment]
Процесс который обрабатывает отложенные, берет все ТТ у которых есть надпись отложено и дальше смотрит даты, если дата наступила убирает слов о отложено.

Процесс который работает со статусами - выбирает ТТ у которых статус пауза и дальше смотри даты, если дата меньше чем сейчас, меняет статус на  в работе.
При такой схеме они друг другу мешать не будут

Нет ну конечно может быть момент когда поставили паузу а затем отложили- Тогда дата возвращения из статусов будет установленна последним изменением в этом поле, ну да и бог с ними с такими случаями.

**Comment by panches** [comment]
Изменил. Файлы (сервер и клиент) выложил. Версии не менял.

**Comment by VsMoroz** [comment]
Еще ошибку обнаружили, если я работаю в своей закладке и кто то добавил мне запись в ТТ, то такой тт становиться курсивом и подчеркнутым, как только я на него нажимаю - окно обновляется и я вижу все ТТ в моей закладке, вместо того что бы видеть только те ТТ которые статусы которых я отфильтровал вверху в фильтре статусоу.

**Comment by VsMoroz** [comment]
Продолжение темы с некорректным возвращением из состояния Пауза:
Есть ТТ который находится в статусе  Пауза, партнеры, у него такие поля: sostoyanie = в работе, otlogeno_data = 2002-09-15,otlogeno_time = 17:31:00.
Сервер последний вчерашний 1.9.11
По логике  время возвращения из состояния паузы прошло еще в 2002 году, почему робот не возвращает этот ТТ из состояни Пауза в состояние "В работе" ?

Ты же говорил что проверил логику - а здесь как то совсем не работает

**Comment by VsMoroz** [comment]
И еще одно наблюдение, при добавлении записи в ТТ, фокус на этом ТТ теряется, в старой версии не терялся, после добавления ТТ, фокус возвращался на тот Тт в который добавлялась запись

**Comment by panches** [comment]
Замечание по последнему коменту: в предыдущих версиях фокус возвращался на последнюю запись.

**Comment by panches** [comment]
комент №1: обновление исправил
комент №2: исправил ошибки: в сервере не обнулялось поле sostoianie, а в клиенте не верный формат времени передавался.
Файлы выложил, версии не менял.

**Comment by VsMoroz** [comment]
Комментарий про потерю фокуса, я взял версию 5.45.39 - там ничего подобного нет, фокус с ТТ не теряется, после добавления записи в ТТ, фокус остается на этом же ТТ (и не улетает вниз как на новой версии)

**Comment by VsMoroz** [comment]
Запустил новый сервер и клиент, но вот этот ТТ никак не хочет возвращаться из Паузы, хотя ему пора вернуться еще в 2002 году
<code>
INSERT INTO `trubl` (`num_of_trubl_tick`, `inv_num_kli`, `date_of_start`, `time_of_start`, `date_of_end`, `time_of_end`, `description`, `name_user`, `type_trubl_d`, `prichina`, `sostoyanie`, `type_1`, `type_2`, `type_3`, `zakril`, `priority`, `otlogeno_data`, `otlogeno_time`, `otlogeno_name`, `user_id`, `depend_on`, `depend_lbl`, `ring_on`, `state_tt`, `master_tt`, `tab_on`, `date_of_open`, `date_of_close`, `last_zapisi`, `in_num`, `col_centr`, `probl_ind`, `esc_level`, `view_tt`, `master_info`, `email_send`, `email_doing`, `klient_contact_phone`, `status_tt`) VALUES
(326991, 155, '2015-09-01', '12:36:01', '0000-00-00', '00:00:00', 'Авария по температуре', 'Бутенко Максим', 2, '', 'в работе', '', '', '', '', 3, '2002-09-15', '17:31:00', '', 2300034, 0, 0, 0, 1, 0, 3, '2015-09-01 14:36:18', '0000-00-00 00:00:00', '2015-09-03 11:28:45', 0, 0, 0, 0, 0, '', '', 'open', 0, 3);
</code>

**Comment by panches** [comment]
Отсчет идет с 2004 :)

**Comment by panches** [comment]
По фокусу: при добавлении записи есть функционал с статусом ТТ. Вот это и добавило обновление.

**Comment by panches** [comment]
Сервер выложил. Ограничение снизу по времени убрал.

**Comment by VsMoroz** [comment]
Вот этот ТТ тоже не хочет выводить из паузы у него дата и время нули и статус пауза.
Ну вроде ж должен возвращать назад,  нули это же меньше чем текущее время ? 

<code>
INSERT INTO `trubl` (`num_of_trubl_tick`, `inv_num_kli`, `date_of_start`, `time_of_start`, `date_of_end`, `time_of_end`, `description`, `name_user`, `type_trubl_d`, `prichina`, `sostoyanie`, `type_1`, `type_2`, `type_3`, `zakril`, `priority`, `otlogeno_data`, `otlogeno_time`, `otlogeno_name`, `user_id`, `depend_on`, `depend_lbl`, `ring_on`, `state_tt`, `master_tt`, `tab_on`, `date_of_open`, `date_of_close`, `last_zapisi`, `in_num`, `col_centr`, `probl_ind`, `esc_level`, `view_tt`, `master_info`, `email_send`, `email_doing`, `klient_contact_phone`, `status_tt`) VALUES
(326801, 33424, '2015-08-31', '08:57:34', '0000-00-00', '00:00:00', ' Прошу рассмотреть и устранить причину потерь на канале услуги', 'Пташкин ', 3, '', 'в работе', '', '', '', '', 2, '0000-00-00', '00:00:00', '', 2700130, 0, 0, 1, 1, 0, 7, '2015-08-31 08:58:56', '0000-00-00 00:00:00', '2015-09-03 14:37:27', 0, 0, 0, 3720, 0, '', '', 'open', 0, 3);
</code>

**Comment by panches** [comment]
sostiyanie = 'в работе'

**Comment by VsMoroz** [comment]
мы паузу анализируем, это поле  status_tt нам все равно какое там значение в поле sostiyanie ;)

**Comment by panches** [comment]
Возвращаемся в начало переписки и повторим ошибки? Для этой записи обнули поле sostoyanie и status_tt:=2, больше таких записей повторяться не будет.

**Comment by panches** [comment]
Потеря фокуса при добавлении записи, исправил. v5.45.47, файл выложил.

**Comment by VsMoroz** [comment]
Нашли еще одно: при добавлении записи в ТТ из закладки  Trouble Ticket - "Поиск TT" последняя версия не позволяет этого т.к. в форме добавления ТТ нет поля статус - выдает ошибки.

По ниже процетированному: здесь я не понял преимуществ  на мое предложение сделать процессы вывода из отложенных и из паузы , сделать его  объемным и всеохватывающим (тоесть учесть и случаи когда дата время = нулю), ты предлагаешь оставить мину в виде не реагирования системы на нули. 

Зачем ? В чем преимущество  ?

> Возвращаемся в начало переписки и повторим ошибки? Для этой записи обнули поле sostoyanie и status_tt:=2, больше таких записей повторяться не будет.

**Comment by panches** [comment]
Ошибку исправил. v5.45.48

Процесс я вижу так: 
- В пауза (состояние = "Пауза..." и status_tt={3,4})
- Из паузы (проверка (состояние = "Пауза...") то {сотояние = '' и status_tt=2})

нет пересечения с отложенными и подводных камней не наблюдаю.

Опиши свое видение.

**Comment by VsMoroz** [comment]
Запрос определяет что выводить из отложенных:
<code>SELECT \*  FROM `trubl` WHERE `sostoyanie` LIKE 'отложено' and concat(otlogeno_data, ' ',otlogeno_time) < now()</code>

Запрос определяет что выводить из паузы:
<code>SELECT \*  FROM `trubl` WHERE status_tt IN(3,4) and concat(otlogeno_data, ' ',otlogeno_time) < now()</code>

**Comment by panches** [comment]
Запросы заменил, v1.9.13

**Comment by VsMoroz** [comment]
Про это не забыл ? 

> Нашли еще одно: при добавлении записи в ТТ из закладки Trouble Ticket - "Поиск TT" последняя версия не позволяет этого т.к. в форме добавления ТТ нет поля статус - выдает ошибки.

**Comment by panches** [comment]
Я написал выше (3-е сообщение), это сделано.

**Comment by VsMoroz** [comment]
Ты проверял ? Поставь последнюю версию из нашего файлового хранилища, удастся добавить запись ?

**Comment by panches** [comment]
Я проверял, а ты?

**Comment by VsMoroz** [comment]
Проверял, меня смутило то что при обычном добавлении записи - присутствует поле "Статус Тт" при добавлении записи из закладки Поиск - она не присутствует, ну ок, пусть так и будет.

А чего при добавлении записи через Поиск ТТ - меня перебрасывает не в активные ТТ  а в отложенные ?

**Comment by panches** [comment]
Могу сделать, чтобы перебрасывало в Поиск ТТ

**Comment by VsMoroz** [comment]
Да в поиск ТТ будет правильно

**Comment by panches** [comment]
выполнил, версию не менял

**Comment by VsMoroz** [comment]
Вроде нормально все, тестируем.
Пока вопрос закрываю, мы еще к нему вернемся, нужно будет навернуть автоматику, но это попозже, сейчас займемся SLA и полуавтоматизацией приема в эксплуатацию

**Comment by VsMoroz** [comment]
При попытке добавить ТТ в отложенные вываливается ошибка

**Comment by VsMoroz** [comment]
Да действительно у пользователя была старая версия. Поставили нормальную версию и все стало ОК.

Там проявилась новая проблема с подчиненными ТТ, при закрытии материнского ТТ  ( или переводе его в состояние У) не заполняются подя  в подчиненных ТТ данные о дате времени закрытия, о причинах . Это все приходится вручную. раньше (напомню) инженер после подтверждения клиента просто нажимал кнопку закрыть ТТ и видел все поля для закрытия уже заполненные

**Comment by panches** [comment]
Этот функционал был выведен в сервер, а в Клиенте закрыт. Когда это случилось я не помню.

**Comment by VsMoroz** [comment]
Да он был выведен в сервер, но он работал, а сейчас не работает.

**Comment by panches** [comment]
Не распределяются ТТ в очередь или не закрываются подчиненные ТТ без очереди? Какие признаки не работы?

**Comment by panches** [comment]
Ошибку исправил, v5.45.49

**Comment by VsMoroz** [comment]
Давай попытаемся сделать отображение в Активных ТТ подобным тому которое было в компоненте без статусов. 
Тоесть вот запусти рядом старую и новую версию,возможно ли сделать в новой версии такую же высоту строк, размер и тип шрифта ?

**Comment by VsMoroz** [comment]
И себе я ставлю задачу что бы не забыть, поправить все даты отложенные, потому что предыдушая неправильно работающая наштамповала под две сотни спутниковых отложенных ТТ на демонтаж с возвращением из отложенных в 2016 году

**Comment by panches** [comment]
Поигрался с отображением, мне кажется так будет нормально. Версию не менял.

**Comment by VsMoroz** [comment]
Привет ! 
После исправления обнаруженных ошибок, ты проверял  они действительно устранены ? 

Ниже указанная ошибка не исправлена, проблема сильно усугубляется тем что новая версия уже у всех и сильно страдают подразделения первой линии.

при закрытии материнского ТТ ( или переводе его в состояние У) не заполняются подя в подчиненных ТТ данные о дате времени закрытия, о причинах . Это все приходится вручную. раньше (напомню) инженер после подтверждения клиента просто нажимал кнопку закрыть ТТ и видел все поля для закрытия уже заполненные

**Comment by VsMoroz** [comment]
Так же существует ошибка и с подчиненными ТТ открытыми по сигналу NMS
Такие ТТ должны были закрыться самостоятельно (после закрытия материнского) - этого не происходит  ТТ назначаются оператору как будто они открыты по обращению клиента

**Comment by panches** [comment]
По второму вопросу: раньше все "подчиненные" распределялись по очередям. Исправил, сейчас только type_trubl_d=3 распределяюся. v1.9.15

По первому: должно все работать. Давай понаблюдаем после изменения в сервере.

**Comment by VsMoroz** [comment]
Type 3 будет распределяться по очередям, ок, проверим. 
А Type 2 - с ними что будет ? 

В сервере ты кроме  процитированного что нибудь еще исправвлял ? "Исправил, сейчас только type_trubl_d=3 распределяюся. v1.9.15"

Так же заметил сегодня что если переводить в статус Паузы  после 20:01 - то суммарное время до когда поставить ТТ на паузу выставляется неправильным, вернее  - время выставляется корректно, а дата не изменяется, вместо того что бы выставить на 01:00 следующего дня, выставляется на 01:00 текущего дня (что является уже прошедшим временем)

**Comment by panches** [comment]
type_trubl_d=2 - автоматически закрывается

**Comment by panches** [comment]
Ошибку с временем исправил, v5.45.50

**Comment by panches** [comment]
Отображение значений (если они там есть) в полях (причина, классификация) з-ка Закрыть ТТ - восстановлено.
Отображение названий закладок в з-ке БАЗА - восстановлено.
v5.45.51

**Comment by VsMoroz** [comment]
Красота, действительно надписи закладок вернулись, пауза выставляет правильную дату.

**Comment by VsMoroz** [comment]
По многочисленным просьбам пользователей прошу :
1. В закладке активных ТТ переименовать кнопку "Отложить" на Статус, пиктограмму пока не меняем.
2. При нажатии на кнопку что бы открывалось меню со списком статусов и работал весь действующий на меню функционал статусов.
3. Пример для наглядного представления высылал по email сегодня.

**Comment by panches** [comment]
выполнил, v5.46.26

**Comment by VsMoroz** [comment]
Спасибо. тестируем

**Comment by VsMoroz** [comment]
Разрабатываю запросы для возвращения ТТ из Паузы, сейчас мы его просто возвращаем тому за кем он закреплен.

Модернизация будет касаться назначения ТТ, если его пора возвращать из Паузы нужно будет : 
-если текущее рабочее место в работе - назначить ТТ на него
- если текущее недоступно - на свободное доступное место в группе
- если в группе нет ни одного свободного - на свободное рабочее место в секторе в котором есть активность (определяется по  самой последней запись в любой ТТ)

Как доделаю запросы - пришлю запрос будет получать номер ТТ и возвращать user_id который нужно присвоить ТТ, вот он b6eef87e6750e7fe1c87f5693189b8aae0b95588

**Comment by VsMoroz** [comment]
Есть добавил: b6eef87e6750e7fe1c87f5693189b8aae0b95588

**Comment by panches** [comment]
Меня смущает скорость работы запрося (у меня один запрос считало на моем компе! аж 57,7 сек.).
Может есть смысл разбить на несколько простых запросов?

**Comment by panches** [comment]
запрос добавил, v1.9.22

**Comment by VsMoroz** [comment]
Прошу изменить вносимую в ТТ запись при установке ТТ статусов 3 и 4 (Пауза, партнеры, Пауза, клиент)

При установке этих статусов во вноосимую запись в ТТ:
- в поле zapisi_trubl_tic.name_user - вставлять имя залогиненного пользователя
- в поле zapisi_trubl_tic.kontakt  вносить  название устанавливаемого статуса брать его из tab_status_tt.forIngener
- из текста вписываемого в  zapisi_trubl_tic.desc_zapisi исключи выделенное жирным: **Пауза, клиент,** До : 12:57 18.03.16, до инфо от клиента

**Comment by panches** [comment]
изменил, v5.46.36

**Comment by VsMoroz** [comment]
Работает, спасибо

**Comment by VsMoroz** [comment]
По статусам прошу следующую модернизацию для ТТ которые находятся в подчинении:
1. Если ТТ подчиняется он должен получить такой же статус как у материнского ТТ (Если это Пауза то у ТТ должен получить ту же дату выведения из Паузы)
2. Если у материнского ТТ меняется статус, то у подчиненных он должен меняться на такие же.

**Comment by panches** [comment]
модернизировал, v5.46.37

**Comment by VsMoroz** [comment]
Спасибо, хорошо !
