### ISSUE TITLE
SLA каталог ввести в систему

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#56]
Введем в систему SLA каталог (то о чем долго говорили большевики :) ) , а затем на его  основании настроим работу очередей .

Ключевое отличие от существующей системы, уровень детализации "услуга" (раньше уровень был "клиент"

**Comment by VsMoroz** [comment]
План:
1.Создаем под каждый тип таблицу в которой будут экземпляры  данного типа SLA
2.В каждой таблице обязательно пометка какой SLA по умолчанию. он не может иметь ограничений по сроку действия и по области видимости
3.В каждой таблице с услугами, вводим два поля, название SLA  таблицы и  ID экземпляра 

В каждом экземпляре область видимости СЛА, по клиенту и по периоду времени.
Таблицы я допишу сегодня завтра.

**Comment by VsMoroz** [comment]
Добавляем 2 поля в таблицу СК что бы ссылаться на SLA:
А так же создаем таблицу с SLA( в примитивном виде, там сейчас только ID, название и короткое название)
ae2e8ec8bf7f57015df3487fa111a4a3cce377c6

Сейчас мы будем реализовывать только интерфейс привязки СЛА к СК и отображения его в активных ТТ, без аналитики.
Модернизируй форму добавления и редактирования СК, что бы поле SLA был выпадающий список с значениями:
<code>
SELECT CONCAT(`name`,' (',`lbl`,')') AS slnm FROM `tab_sla_net_data`  ORDER BY `id` ASC
</code>

По умолчанию 'ид выбранного сла' = 
<code>
SELECT id FROM `tab_sla_net_data` WHERE `dflt` =1 ORDER BY `id` ASC LIMIT 1
</code>

При сохранении СК записывалось :  net_data.sla_d = 'tab_sla_net_data' , net_data.sla_id='ид выбранного сла'

*!! Важно форма добавления СК есть как в  закладке СК, так и в визарде.

**Comment by VsMoroz** [comment]
После выполнения предыдущего комментария, добавь поле 'sla' в закладку Активные ТТ между полями 'pri' и 'Клиент'  если это СК - заполни эти поля значениями из tab_sla_net_data.lbl

**Comment by VsMoroz** [comment]
После выполнения предыдущего комментария, добавь информацию о названии SLA в информационное окно всплывающее по двойному щелчку на ТТ (открытого на СК) или на СК в закладке СК.
В строке CID: D999999 поставь запятую и добавь (жирным)  SLA: (не жирным) название SLA по запросу

<code>
SELECT CONCAT(`name`,' (',`lbl`,')') AS slnm FROM `tab_sla_net_data` WHERE tab_sla_net_data.id = net.data.sla_id(из этого СК)   LIMIT 1 
</code>

**Comment by panches** [comment]
Изменения внес, v5.46

p.s. wizzard не забыл!

**Comment by VsMoroz** [comment]
Привет, добавим выделение жирным значения поля SLA  в закладке активных ТТ, только поля SLA  и только для тех SLA у которых в поле  tab_sla_net_data.bld = '1' - это поле добавил последним коммитом 4f7b3efbd6a2e653c60ecf17b7797da217f2169f

**Comment by panches** [comment]
Изменения выполнил, файл выложил, v5.46.01

**Comment by VsMoroz** [comment]
Привет ! 
Цвет опять съехал с поля "Статус" на поле "Причина открытия"

**Comment by panches** [comment]
Исправил ошибку, v5.46.02
