### ISSUE TITLE
Засбоила рассылка отчетов по СтОП

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#58]
Произвел изменения в настройке рассылки ежемесячных отчетов по Стоп, заменил  -7  на -8 в параметре start поля `period_d` таблицы   `email_distribution` и появилась проблема данные робот отсылает не каждую неделю а через неделю.

Это видно по полю 'sended' последняя отсылка была 29.06.15  после этого должна была быть отсылка  06.07.15 но ее не было. (данные сняты сегодня)

Напомни что может мешать отсылке еженедельно ? 

INSERT INTO `email_distribution` (`id_distr`, `name_distr`, `period_d`, `recipients`, `description`, `sended`) VALUES
(1, 'channel_subprovider_report', 'dayOfMonth=*;dayOfWeek=1;hours=06;start= ~~-7~~ -8;stop=-1;', '546;338;6;307;595;344;361;', 'Еженедельная отсылка отчета по каналам арендуемым у субпровайдера', '2015-06-29'),

**Comment by panches** [comment]
Сегодня должно прийти письмо (период на день увеличился)

**Comment by VsMoroz** [comment]
Все работает ровно так как я написал, письма ходят через неделю, а должны ходить каждую неделю.
Параметр который говорит когда должен быть отправлен отчет он вот здесь: dayOfWeek=1

Я же поменял период анализа, тоесть то что определяет глубину выборки.

Что может мешать отправляться отчету каждую неделю ?

**Comment by panches** [comment]
Мешает это:
(DaysBetween(dd,DataModule1.ADQuery11.FieldByName('sended').AsDateTime)>=j), где 
  j:=ABS(dStart)-ABS(dStop)+1;
Откуда она взялась я уже не помню.

**Comment by VsMoroz** [comment]
Эта проверка она стоит где, перед запуском процесса  ? Помню при запуске этого модуля была проблема с тем что программа отсылала несколько копий, потом не хотела  отсылать чаще чем 1 раз в неделю. Вот тогда возможно и появилась эта проверка. 
Ты можешь посмотреть если проверку убрать  -  программа будет при наступлении дня и времени отсылки отчета - отсылать его 1 раз ?

**Comment by panches** [comment]
Если этот процесс будет обновляться чрез 1 час + 1 минута, то можно убирать.

**Comment by VsMoroz** [comment]
А как сейчас часто он обновляется ? 
Я точно не планирую делать рассылки чаще чем раз в час, потому что у нас в параметре старта процесса минимальная цена деления 1 час (hours=06;)

**Comment by panches** [comment]
tab_setup_serv - таблица, поле time2 (минут).

**Comment by VsMoroz** [comment]
Ты можешь досетапить что бы  серверная часть пыталась запускать этот процесс только в промежутке между  00 - 15 минутами того  часа в который настроен в email_distribution.period_d -  hours=06; 
А так же после выполнения процесса , серверная часть у себя в памяти запоминала  что процесс уже запускался.

**Comment by panches** [comment]
Я подумаю как это сделать

**Comment by panches** [comment]
Сделал так: проверяю количество дней прошло с последней рассылки (поле sended), если больше 1, то если остальные условия (день, час) проходят, то отсылается письмо.

**Comment by VsMoroz** [comment]
Запустил серверную часть, проверим в течении двух недель

**Comment by VsMoroz** [comment]
Есть проблема, эта версия присылает файлик с отчетом всем подписантам, но в нем не заполнено ни одно поле. Пример пришлю почтой

**Comment by panches** [comment]
Проверил, файл заполняется. Объяснение: все sql-запросы были пустыми (сбой сервера, или ...) и поля остались не заполненными.

**Comment by VsMoroz** [comment]
Сделаем паузу по этому вопросу, давай пилить статусы ТТ

**Comment by VsMoroz** [comment]
Все работает.
