### ISSUE TITLE
ТТ система и ноутбук

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#60]
Привет ! 
Сейчас работаю с ноутбука и если его отключаю от корп сети ( а это бывает часто) то система ТТ и учета бух документов насыпают  кучу алармов о том что сервер недоступен.
Насколько хлопотно модернизировать софт что бы программа проверяла перед отправкой запросов, есть ли коннект с сервером и только тогда слала, если нет - то не слала (соответственно и ошибок не будет)

**Comment by panches** [comment]
Как раз перед запросом программа и проверяет существование коннекта. А ошибки возникают из-за таймеров, которые проверяют новую версию и отображение в строке сосотояния (Клиент)

**Comment by VsMoroz** [comment]
Никто ж не отрицает что программа проверяет
Как сделать что бы программа не насыпала миллион окон о том что нет доступа к серверу ? А показывало только одно ?

**Comment by panches** [comment]
Сделать для таймеров особый режим - без алармов.

**Comment by panches** [comment]
Reest - файл выслал, в Клиенте такой проверки нет.

**Comment by VsMoroz** [comment]
Да было бы хорошо что бы система проверяла при запуске таймера и если нет коннекта к серверу то не пыталась слать запросы

**Comment by panches** [comment]
Так и делается: сначала наличие коннекта, а затем запрос.

**Comment by VsMoroz** [comment]
Сейчас система шипет ошибками, сделаю скриншот пришлю

**Comment by panches** [comment]
v1.01.71 в таймере изменил проверку коннекта с сервером, должно помочь.

**Comment by VsMoroz** [comment]
Это ты в бух учете изменил, или в БДСЭ ?

**Comment by panches** [comment]
reesrt.exe

**Comment by VsMoroz** [comment]
А для системы ТТ так можно сделать ?

**Comment by panches** [comment]
если это работает, то конечно.

**Comment by panches** [comment]
Выполнил, v5.45.39

**Comment by VsMoroz** [comment]
Система ТТ работает супер, при отсутствии сети и отсутствии активности ошибками не сыпет !

А вот система учета бух документов по прежнему выдает ошибку " Не удалось подключиться к mysql"
Какойто таймер в фоне куда то стучиться, куда ? Можно его приостанавливать если нет коннекта ?

**Comment by panches** [comment]
Выложил вариант, должен работать. Смотри GoogleDisk.

**Comment by VsMoroz** [comment]
Софт вижу, поставил, тестирую (после установки слетели настройки ширины полей) раздвинул поля вручную

**Comment by VsMoroz** [comment]
Версия 1.01.71 - все таки ругается если  я переношу ноут с места на место ( в течении полу часа без сети) говорит потеряная связь  с сервером

**Comment by panches** [comment]
Поменял "ругательства" (необходимо для понимания). Файл в том же месте.

**Comment by VsMoroz** [comment]
Проинсталил файл, запустил, отрубил сеть ~ через 15 минут получил такую инфо: "Потеряна связь с сервером MySQL"

**Comment by who0ps** [comment]
Ошибки, которые появляются во время отправки запроса без коннекта к сети. **4** штуки.

---------------------------
Error
---------------------------
[AnyDAC][Phys][MySQL][LIBMYSQL] Lost connection to MySQL server during query
---------------------------
OK  
---------------------------

---------------------------
Error
---------------------------
[AnyDAC][Phys][MySQL][LIBMYSQL] MySQL server has gone away
---------------------------
OK  
---------------------------

---------------------------
Error
---------------------------
[AnyDAC][Phys][MySQL][LIBMYSQL] MySQL server has gone away
---------------------------
OK  
---------------------------

---------------------------
Clientsdb
---------------------------
ADQuery17: Cannot perform this operation on a closed dataset.
---------------------------
ОК  
---------------------------

**Comment by VsMoroz** [comment]
Так и должно быть. Именно такое поведение системы и было заложено

**Comment by VsMoroz** [comment]
Уже не актуально
