### ISSUE TITLE
Фильтрация областей в Форме добавления города в систему ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#61]
Привет ! 
Система ТТ, Tools -> Options -> перейти на закладку "Таблицы"  -> в поле "Выбор таблицы" выбрать "Город"    подправь код что бы при выборе в этой форме Страны, соответсвенно менялись значения в форме "Область", а то сейчас независимо от выбора страны - список Областей содержит в себе все области.

**Comment by panches** [comment]
Выполнил, v5.45.39

**Comment by VsMoroz** [comment]
Все гуд, спасибо !
