### ISSUE TITLE
Гонять дистрибутивы не почтой а через google dirve

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#62]
Привет ! 
Упорядочим отсылку дистрибутивов.
Скачай программу google drive, зарегистрируйся, создай в нем папку Датагруп  и расшарь ее мне.
Внутри мы создадим две папки CliendDB и Reestr  и вместо того что бы каждую новую версию программы гонять по почте, ты будешь просто ложить их в эти папки и все, а я их буду от туда забирать.
Там хранилище большое, можно старые не удалять, просто добавлять новые.

**Comment by panches** [comment]
Создал папки, подписал rf400rt. Видиш папку?

**Comment by VsMoroz** [comment]
Назови ее DataDistributive и пришли мне приглашение, нажми на ней правой кнопкой мыши выбери Поделиться и оно само запросит мой email

**Comment by panches** [comment]
Послал приглашение

**Comment by VsMoroz** [comment]
Спасибо, все гуд

**Comment by VsMoroz** [comment]
Ты себе приложение поставил и папка тебе видна как папка на жестском диске, или через браузер пользуешься ?

**Comment by panches** [comment]
И так и так.

**Comment by VsMoroz** [comment]
С папкой на компе оно удобней :)
А лазить в браузер это не дело.

**Comment by panches** [comment]
На XP я буду ложить прямо в папку.

**Comment by VsMoroz** [comment]
У меня  win 8 там тоже этот вариант с папкой работает, просто скачать приложение и оно само будет лазить в выделенную папку и синхрить с гугл драйвом.

На вин 7 я думаю так же.

**Comment by panches** [comment]
На 7 работает, на XP - нет.

**Comment by VsMoroz** [comment]
Странно, должно бы работать.
