### ISSUE TITLE
(не срочно) Добавить название области во всплывающее информационное окно на СУ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#63]
При двойном тапе на СУ или на ТТ открывается информационное окно, добавить в него инфо о Области (спутники просят)

**Как есть:** 
Tooway
dhcp 
СУ - RTLC-110652 - InetBOOM, Диброво, Краснолиманский, Пушкина 15

**Как сделать:**
Tooway
dhcp 
СУ - RTLC-110652 - InetBOOM, Диброво, Краснолиманский, Пушкина 15 (Луганская обл)

**Comment by panches** [comment]
Выполнил, v5.45.46. Файл выложил.

**Comment by panches** [comment]
Выложил еще раз.

**Comment by VsMoroz** [comment]
Я области не вижу при двойном щелчке на активный ТТ, ты видишь ?

**Comment by VsMoroz** [comment]
Во, версия обновилась, теперь вижу. Тестируем

**Comment by VsMoroz** [comment]
Спасибо работает !
