### ISSUE TITLE
Добавить CID в шаблон email который отсылается клиентам. 

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#64]
Привет ! Давано собирались это сделать, назрела необходимость сделаем это теперь.
- добавляем CID  в шаблоны открытие/апдейт/закрытие
- если ТТ открыт на объект у которого нет CID - то заголовок CID:  в тело письма не вставлять
- CID есть только у СК
- CID должен быть размещен следующей строчкой после названия услуги и иметь формат 
  CID: ETH100144

**Пример:**

Open TT: #327 537
### :  Ресторан, метелица, доступ в интернет,

CID: ETH100114 
/-----

Во всех шаблонах открытие/апдейт/закрытие - такой формат размещения CID

**Comment by panches** [comment]
Выполнил, v1.9.12, файл выложил

**Comment by VsMoroz** [comment]
Смотрю у ТТ открытого на ТП - тоже стоит слово CID  в письме, глянь еще раз второй пункт, если обьект не СК или (СК - но у него нет CID )- то слово CID  в письмо не вставлять.

---

TT: #327 824 - Close 
06.09.15 22:18 (UTC+3)
-------\

Open TT
06.09.15 17:47

##:  192.168.205.12, inpChange: Input changed to alarm in Rectifier Alarm

###:  ТП - Киев,  126
CID:

**Comment by VsMoroz** [comment]
И еще дополнение в net_data  поле cid по умолчанию имеет значение 0, если у СК такое значение то такой CID  тоже не надо показывать

**Comment by panches** [comment]
Подставил проверку на номер таблицы (№7), также учитывается при проверке пустая строка и ноль. Номер версии не менял.

**Comment by VsMoroz** [comment]
Чего то CID  не появился в шаблоне -апдейт.
Пример пришлю почтой

**Comment by panches** [comment]
Ошибку нашел, исправил. v1.9.14

**Comment by VsMoroz** [comment]
Нормально, появляется, везде. Закрываю вопрос, спасибо.
