### ISSUE TITLE
Добавить инфо о Менеджере и Номере задачи планера,  в информационное окно ОК

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#65]
Привет ! 
Переформатируй пожайлуста информационное окно ОК (появляется в закладке ОК или при двойном щелчке на Активный ТТ открытый на ОК)

Инфо о менеджере и номерезадачи из планера с таким же форматированием как это делается в  информ окне СК.
Убрать строчку "ID в планере: 280086"
А номер задачи перенести вниз к менеджеру, что бы и по цвету и по стилю было точно так же как в СК

Пример:
**Менеджер:** Гарна О, **№ в планере:** 13453322

**Comment by panches** [comment]
Выполнил, v5.45.47, файл выложил

**Comment by VsMoroz** [comment]
Спасибо, работает, закрываю
