### ISSUE TITLE
База данных для СТОП, изменить на СК, значение в инфо блоке "Привязать" СК (мелочь)

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#66]
База, закладка Сервисы субпровайдеров,форма создания записей, Информационный блок "Привязать", значение "База" измени его значение по уполчанию с СС на  СК 

Я ж говорю (мелочь) :)

**Comment by panches** [comment]
Выполнил, v5.45.47, файл выложил.

**Comment by VsMoroz** [comment]
Спасибо, работает
