### ISSUE TITLE
Уберем / и \ из шаблонов email рассылки

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#67]
Привет ! 
Убери пожайлуста \ и / в шаблонах рассылки email  по событиям:
-создан ТТ
-апдейт ТТ
-закрыт ТТ

Я имею ввиду вот это:
-------\
/-------

Уберем только косые, сами прочерки пусть остаются.

**Comment by panches** [comment]
Выполнил, v1.9.14

**Comment by VsMoroz** [comment]
Этот вопрос тоже решен.

Давай здесь так же  решим еще технический долг с процедурой email оповещения по алгоритму "апдейт".

Бывают случаи что  инженеры добавляют с интервалом в минуту две официальных версии, в таких случаях робот шлет два абсолютно одинаковых письма.

Как бы сделать что бы робот слал только одно письмо ?

**Comment by panches** [comment]
Один инженер - одна задача.

**Comment by VsMoroz** [comment]
Так один и тот же инженер добавляет, но все равно если два добавленния успели произойти между  срабатываниями этого процесса  - то робот шлет два идентичных письма - можем убрать этот дубляж что бы робот слал одно.

**Comment by panches** [comment]
Убрать можно все. Как?

**Comment by VsMoroz** [comment]
Провести инспекцию алгоритму, наложить на него ситуацию описанную мной и увидеть почему дублирующие письма приходят. Я подозреваю что дублирование  происходит потому что ты запускаешь в цикле процесс "апдейт" в рамках одного ТТ, количество итераций в цикле ты просчитываешь из  количества записей в этом ТТ которые нужно отправить. Но т.к. отправляешь ты все обновления (тоесть все старые апдейты по ТТ и все новые вместе в одном письме) то получается что цикл в рамках ТТ не нужен, потому что первая же итерация отошлет все обновления из ТТ, а вторая просто продублирует первое письмо.

**Comment by panches** [comment]
Ты предлагаешь: запрос (DESC) и добавлять только первую запись?

**Comment by VsMoroz** [comment]
Где я такое предлагаю ? 
Я предлагаю избежать отсылки просто двух одинаковых писем - которое происходит в описанной мной ситуации

**Comment by panches** [comment]
Ты не правильно понимаеш слово цикл. Цикл в данном случае работает так: 1)Делается запрос всех записей к ТТ 2) дальше цикл: берем первую запись - формируем сроку в теле письма, зтем берем вторую зпис  - формируем строку в теле письма и т.д. пока записи не закончатся. 3) конец цикла.

**Comment by VsMoroz** [comment]
Я правильно понимаю, нужен дистинкт по полю номера ТТ или переделать алгоритм что бы цикл строился на уровне ТТ а ТТ отбирались по принципу только одна запись на каждый ТТ и только те ТТ в которых появилась хотя бы одна запись апдейта которую нужно отослать

**Comment by panches** [comment]
Это новая задача, сейчас работает так как я описал.

**Comment by VsMoroz** [comment]
С одной стороны новая, а с другой не такая и новая :)
Давай здесь так же решим еще технический долг с процедурой email оповещения по алгоритму "апдейт".

Бывают случаи что инженеры добавляют с интервалом в минуту две официальных версии, в таких случаях робот шлет два абсолютно одинаковых письма.

Как бы сделать что бы робот слал только одно письмо ?

**Comment by VsMoroz** [comment]
?

**Comment by panches** [comment]
Как программно узнать какая запись правильная, а какая нет? Я не представляю как это сделать.

**Comment by VsMoroz** [comment]
Там же очень просто: каждая запись имеет инфо о номере ТТ, а так же инфо о том отсылалась ли запись клиенту или нет, если  zapisi_trubl_tic.transition = 61 то запись  тредует отправки клиенту если 62 то она уже отправлена.
Запрашиваем у БД все ТТ по которым есть записи с 61 - обязательно с дистинкт, что бы избежать дубляжей письма как у нас сейчас. Затем по каждому письму шлем апдейт письмо, затем во все записи в отосланных ТТ с 61 меняем их на 62

Эта задача не срочная, давай сделаем ее после СЛА,  но сделать надо а то как то несолидно когда система шлет два одинаковых письма серьезному клиенту

**Comment by panches** [comment]
Все что ты описал сервер и делает.

**Comment by VsMoroz** [comment]
Основное что требовалось режить в рамках этого ишью- решено, к вопросу дубляжей писем вернемся как нибудь в другой раз :)
