### ISSUE TITLE
Перевод email оповещения силами гугл, для англоязычных пользователей

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#68]
Привет ! 
В жизни должны быть интересные задачи :) ты пробовал работать когда нибудь работать с API  гугла ? Давай сейчас поисследуем насколько из делфи можно отослать гугловому переводчику текст этого письма и получить его переведенным на английский язык.

Если это удастся, мы в каталоге партнеров добавим поле язык и будем переводить все имыл сообщения для клиентов у которых будет помтка английского языка. Перед бритиш телеком неудобно очень. Робот с ними на русском переписывается :)

**Comment by panches** [comment]
Я дума что можно, но не в Delphi 7

**Comment by panches** [comment]
http://www.webdelphi.ru/2014/10/delphi-xe5-xe7-rabota-s-google-static-maps-api/

**Comment by VsMoroz** [comment]
Да я тоже об этом что там стандартный rest  интерфейс и возможно в делфи его реализовать тоже можно. Ты как оцениваешь, насколь ко это хлопотно ? 

Я пробовал просто скармливать ему полностью наши письма оповещения - ну да .. местами переводит некорректно, но в целом нормально -  в наших реалиях подойдет

**Comment by panches** [comment]
В 7-ке я даже браться не буду.

**Comment by panches** [comment]
Предлагаю сервер перевести на рельсы Delphi XE2 (на нем написан Reestr). Тогда и перевод реализуется без проблем.

**Comment by VsMoroz** [comment]
Это по трудозатратам большая работа ?

**Comment by panches** [comment]
Не могу сказать, надо начать и закончить. Буду работать в промежутках между задачами.

**Comment by panches** [comment]
Сервер в Delphi XE2, v2.0.0. Файл выложил.

**Comment by VsMoroz** [comment]
У меня сейчас пипец с свободным временем (ты это видишь по затишье в наших проектах) проверил весь функционал этого сервера ?

**Comment by panches** [comment]
Отсылку писем проверить не могу. В коде изменений мизер, необходимо тестить.

**Comment by panches** [comment]
По переводу:
Похоже есть проблема (услуга платная)
https://cloud.google.com/translate/?utm_source=google&utm_medium=cpc&utm_campaign=2015-q1-cloud-emea-gce-bkws-freetrial-en&gclid=CJrHlZT7k8gCFWrkwgodSn0Nhg
По крайней мере необходим "google api key" для работы в v2 ( v1 устарела и не работает )

**Comment by VsMoroz** [comment]
Какова цена вопроса ? 
http://best-web-creation.com/articles/view/id/google-maps

**Comment by panches** [comment]
Покрути страничку, цена ниже.
Твоя ссылка устарела, инструкция не рабочая.

**Comment by VsMoroz** [comment]
Давай попробуем вот этот апи: https://tech.yandex.ru/translate/

**Comment by panches** [comment]
Да, это лучше. Буду работать с "вражеским"  сайтом ;)

**Comment by VsMoroz** [comment]
Давай попробуем тестовую программу на яндексе,  а затем  я согласую деньги и потом перейдем с российского сервиса на гугловый.

По гугловому сервису миллион символов  - это нам насколько писем хватит ?

**Comment by panches** [comment]
Предположим, что письмо имеет 500 символов, тогда:
1000000 / 500 = 2000 писем.
п.с. Пробую бороться с Яндексом, но пока упираюсь в кодировку.

**Comment by panches** [comment]
Яндекс переводчик сделал, выслал на почту.

**Comment by VsMoroz** [comment]
В дальнейшем ложи на гугл драйв.
В целом переводит ничего. Путается при аббревиатурах и почему то ул Кутузова 30 переводит как Lesi 30 - вердикт - подойдет !

**Comment by who0ps** [comment]
Автоматически отправляемые оповещения о причине инцедента и дате будет проще и намного быстрее перевести вручную и задать соответствие по почте, на которую бот их отсылает.

Адреса перевести адекватно не получится ибо переводчики будут делать перевод того, чего не надо, а транслитераторы не поймут "улица/переулок/бульвар/смт" и пр.

**Comment by VsMoroz** [comment]
> будет проще и намного быстрее перевести вручную

Автоматический перевод и выбор кому в каком языке слать выполнится за 0,1 секунды, неужели вручную быстрее ? 

> и пр.

Что имеется ввиду по  словом пр ? :)

Главная цель автоматического перевода, что бы инженеру не приходилось еще и думать о переводе, его главная задача это сеть, а не оповещение.

**Comment by who0ps** [comment]
> вручную быстрее ? 

Я имею ввиду сделать вручную набор стандартных фраз "в работе" "Просьба проверить" и так далее.
Выбирать язык в соответствии адресата и рассылать, конечно, автоматизированно.

> Что имеется ввиду по словом пр ? :)

Прочее. Сокращения, единицы измерения и другие фразы, что можно встретить в базе.

> не приходилось еще и думать о переводе

Если мы ещё можем понять автоматизированый кривой перевод с англ, то иностранцы с русского будут в недоумении. Автоперевод письма от инженера на клиента - это хорошо, но необходима возможность исправления ошибок переводчика.

**Comment by VsMoroz** [comment]
>Я имею ввиду сделать вручную набор стандартных фраз "в работе" "Просьба проверить" и так далее.

А как быть с текстом, который мы хотим довести до клиента, ну там детали инцидента, его ведь прийдется тоже как то переводить.

> Автоперевод письма от инженера на клиента - это хорошо, но необходима возможность исправления ошибок переводчика.

Штатные средства что гугла что яндекс переводчика подволяют умеют обучать его, прям смотреть как он перевел, выделять неудовлетворяющую часть и корректировать.

**Comment by who0ps** [comment]
> детали инцидента

В любом случае, нужна будет проверка тем же инженером на корректность перевода.

> обучать его

Знаю, но нужны десятки исправлений, чтобы правильный перевод поднялся в списке предполагаемых. 

Есть несколько сотен правок в сообществе переводчика гугла, потому и говорю, что исправления в первой выдаче будут не сразу.

**Comment by VsMoroz** [comment]
Проверка инженером не планируется. Почему ты хочешь вместо упрощения работы инженеру, усложнить ее ? 

Сразу со старта  супер правильный перевод не нужен. Зато обязательно необходима положительная динамика изменений в переводе, это неотъемлемое требование к системе.

**Comment by who0ps** [comment]
Изначально я вообще не говорил о том, что пишет инженер, а об автоматических оповещениях, оправляемых роботом.

**Comment by VsMoroz** [comment]
Буквально предыдущее твое сообщение собержит такой текст: 

> В любом случае, нужна будет проверка тем же инженером на корректность перевода.

**Comment by who0ps** [comment]
> корректность перевода.

Это относится к автопереводу того, что пишет инженер, а не робот. Тут текст изменяется почти каждое письмо.

А то, что отсылает робот - узкий набор фраз, которые должны быть переведены один раз, проверены и сохранены.

**Comment by VsMoroz** [comment]
Письмо собирается из нескольких частей которые содержат и то что пишет человек и то что пишет робот. Перевод какой то части без перевода другой  - ни владельцам ни пользователям ни потребятилем информации от системы ТТ не интересен. Либо весь перевод либо без перевода.

**Comment by VsMoroz** [comment]
Цена на сегодня: https://cloud.google.com/translate/v2/pricing
Вынь да полож 20$ за каждый миллион переводимых символов.

**Comment by who0ps** [comment]
Можно бесплатно юзать API yandex переводчика, если нам достаточно _10 миллионов символов в месяц и не более 1 миллиона символов в сутки._

**Comment by VsMoroz** [comment]
C Яндекс переводчиком работать к сожалению не будем, потому что война между странами :((

Среднее сообщение 550 символов.
На один ТТ нужно в среднем 4 сообщения, это 2200 символов.
На миллион символов (20$) сможем перевести переписку для 454 ТТ 
Будем есть слона по кусочкам.

**Comment by who0ps** [comment]
>  потому что война между странами :((

Эмм... может тогда не пользоваться и сайтами в доменной зоне .ru? 
Тогда почему в этом репозитории всё на русском?


https://www.microsoft.com/en-us/translator/getstarted.aspx
2 млн символов/месяц. Бесплатно.

**Comment by VsMoroz** [comment]
Закрывю этот иишью, дальше поработаем в рамках #102
