### ISSUE TITLE
Trouble ticket -> Все за период - некорректно показывает инфо если дата начала и окончания находятся в разных месяцах

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#69]
Trouble ticket -> Все за период - некорректно показывает инфо если дата начала и окончания находятся в разных месяцах.
Выбираю начало  21.08, окончание 21.09, фильтр по полю Клиент "ощад" - показывает только ТТ за август. За сентябрь не показывает  (хоть они и есть, потому что если выставить 1.09 -21.09 то таких тикетов много показывает)

**Comment by panches** [comment]
При выборе участвуют Дата1 и Дата2. Процедура такая:
если Дата1 = Дата2 то
select \* from trubl where date_of_end = "Дата1"
иначе
select \* from trubl where date_of_end BETWEEN "Дате1" AND "Дате2"

Так это работает. Ничего другого там нет.

**Comment by VsMoroz** [comment]
Я почтой выслал, там ошибка вываливается во времся прокручивания по найденному результату и вот после этой ошибки результат за следующий месяц, пропадает

**Comment by VsMoroz** [comment]
Сегодня ошибки нет. Пока тикет закрываю ( хотя вчера ошибка воспроизводилась стабильно)
Это или ненавидимая мной windows 8.1 pro  или действительно кто то на сервере с БД чет делал
