### ISSUE TITLE
Пользователи с квадратными мониторами жалуются на недоступность поля поиска в БАЗА -> СК

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#70]
Пользователи с квадратными мониторами жалуются на недоступность поля поиска в БАЗА -> СК, у них клиентская часть программы выглядит как  будто не влазит в экран по ширине, пример я пришлю почтой

Разрешение они пробовали разное и 1024х768 и 1280х1024 но результат одинаковый.
Операционная система XP

**Comment by panches** [comment]
уменьшил ширину исходного экрана, v5.45.52
Ширина сдерживается дизайном з-ки АКТИВНЫЕ. Будет мало, буду сужать компоненты.

**Comment by VsMoroz** [comment]
Все стало как было раньше (приемлемо)
Спасибо.
