### ISSUE TITLE
Добавить поля "Тип наряда" и "Cектор"  в закладку Trouble Ticket -> Все выезды 

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#71]

**Comment by VsMoroz** [comment]
Добавить поля "Тип наряда" и "Cектор"  в закладку Trouble Ticket -> Все выезды  и разместить эти поля между полями "Окончание" и "Затрачено"

Их значение брать в точности как берется в таких же полях в закладке Trouble Ticket ->Аварийки

**Comment by panches** [comment]
В закладке таких полей нет. Можно точное название полей получить?

**Comment by panches** [comment]
Добавил, v5.45.53

**Comment by VsMoroz** [comment]
Работает, спасибо !
