### ISSUE TITLE
Сделать задержку в email извещении о открытии ТТ в 20 минут если  ТТ не привязан к объекту

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#72]
Привет ! 
Сделаем задержку в email извещении о открытии ТТ в 20 минут если  ТТ не привязан к объекту.
Планирую это сделать методом корректировки SQL запроса.

Пришли SQL запрос  которым серверная часть запрашивает все ТТ по которым нужно сделать оповещение о открытии ТТ.

**Comment by panches** [comment]
SELECT num_of_trubl_tick, description, email_send, date_of_start, time_of_start, user_id, inv_num_kli, tab_on 
FROM trubl 
WHERE (trubl.date_of_end = "0000-00-00") and (email_send <> "") and (email_doing = "")

**Comment by VsMoroz** [comment]
Чего то не хватает.
Мы не слали по плановым работам, мы не слали если ТТ открыт больше суток назад.
Вытяни запрос прям из программы, какой он ?  (ничего если там будут програмные переменные)

**Comment by panches** [comment]
Поле: Email оповещение о открытии ТТ
SQL - этот
Ограничение по времени <=72 часа
Дальше подготовка к отправке письма.

**Comment by VsMoroz** [comment]
Ты определяешь что это не плановый ТТ и что не прошло 72 часа на уровне делфи, а не на уровне запроса ?

**Comment by panches** [comment]
Плановые не проверяются вообще. А время на уровне программы.

**Comment by VsMoroz** [comment]
По плановым ТТ мы не шлем инфо клиентам, но только в нашей переписке  я не увидел где мы отсеиваем плановые ТТ ?

**Comment by panches** [comment]
Нигде. Возможно в поле (email_send <> "")

**Comment by VsMoroz** [comment]
Не, я точно помню что раньше мы отсылали Тт и по плановым ТТ, а затем допиливали серверную часть, отсеяли их и отсылали только по ошибке НМС или по заявке клиента.

**Comment by panches** [comment]
При открытии ТТ, если в поле Описание есть е-майл, то письмо отсылается.
Письма отсылает только сервер.
Есть еще поле в сервере "Анализ ТТ и записей для отправки писем". Внем анализируются запросы:
- SELECT \* FROM trubl WHERE in_num > "0" and col_centr = "0" and date_of_end = "0000-00-00"
- SELECT \* FROM trubl WHERE in_num > "0" and col_centr = "1" and date_of_end <> "0000-00-00"
- SELECT \* FROM zapisi_trubl_tic WHERE col_centr = "1"

**Comment by VsMoroz** [comment]
Ну попробуй создать ТТ, поставить ему тип ТТ "Плановые работы"  внести в описание Email  и ты увидишь что сервер игнорирует такие ТТ и по ним извещение не отсылает.
Где это проверяется ?

**Comment by panches** [comment]
В плановых поле email_send = "". Это происходит при создании ТТ в Клиенте.

**Comment by VsMoroz** [comment]
Таки да !

**Comment by VsMoroz** [comment]
Модернизировал запрос, согласно моего тех задания:

<code sql>
SELECT num_of_trubl_tick, description, email_send, date_of_start, time_of_start, user_id, inv_num_kli, tab_on 
FROM trubl
WHERE (trubl.date_of_end = "0000-00-00") and (email_send <> "") and (email_doing = "") AND `date_of_open` > ( NOW() - interval 3 day) AND `type_trubl_d` NOT IN(1,4,5,6) AND ((inv_num_kli != '0') OR (inv_num_kli = '0' AND `date_of_open` < (NOW()- interval 20 minute) ))
</code sql>

Глянь свежим взглядом.Запрос я проверил, работает.

**Comment by panches** [comment]
Вроде ровный, подставлю. посмотрим.

**Comment by panches** [comment]
Запрос изменл, v1.9.16 (v2.0.1).
Записи, по которым не отправились письма, я думаю, имеют отношение к проблеме 16254, 16255.

**Comment by VsMoroz** [comment]
Такое ощущение что ты ничего не поменял в сервере 1.9.16

Он шлет письма клиентам по их не привязанным заявкам сразу же после открытия.
Если же я его останавливаю сервер и запускаю новый запрос вручную, там все нормально  ТТ которые не привязанны к обьектам появляются в списке выдаваемом запросом только через 30 минут после их создания.

**Comment by panches** [comment]
```
str:='SELECT num_of_trubl_tick, description, email_send, date_of_start, time_of_start, user_id, inv_num_kli, tab_on '
    +'FROM trubl '
    +'WHERE (trubl.date_of_end = "0000-00-00") and (email_send <> "") and (email_doing = "") '
    +'AND (date_of_open > ( NOW() - interval 3 day)) AND (type_trubl_d NOT IN(1,4,5,6)) '
    +'AND ((inv_num_kli != "0") OR (inv_num_kli = "0" AND date_of_open < (NOW()- interval 20 minute) ))';
Globals.DBSelect(str, DataModule1.ZQuery10); // обращение в БД
DataModule1.ZQuery10.First; // переходим на первую запись
while not DataModule1.ZQuery10.Eof do // пока не конец списка
begin

///         Формирует письмо и отправляет

  DataModule1.ZQuery10.Next; // следующая запись
end;
```

Вот так это работает.

**Comment by VsMoroz** [comment]
Было бы хорошо если работало, но не работает.

Ты проверял  этап компиляции скомпилировал код с новым запросом ? 
После компиляции в гугул драйв ты выложил версию с новым запросом ? 

Здесь наиболее вероятно проблема.

**Comment by panches** [comment]
Перекомпилировал, файл перезалил

**Comment by VsMoroz** [comment]
Не помогло :( подробности письмом

**Comment by panches** [comment]
Добавил Log-файл (время --- Send email for TT #000000). Файлы перезалил.

**Comment by panches** [comment]
В запросе взял в скобки участок (date_of_open < (NOW()- interval 20 minute)). Файл перезалил.

**Comment by panches** [comment]
Из запроса убрал строку: AND ((inv_num_kli != '0') OR (inv_num_kli = '0' AND date_of_open < (NOW()- interval 20 minute) )). Проверка осуществляется сервером. Файл перезалил.

**Comment by VsMoroz** [comment]
Да... какая то проблема с парсингом sql  запроса силами делфи если запрос более менее сложный.

Реализованный вариант когда анализ проводится силами делфи работает. Спасибо.
Закрываю вопрос.
