### ISSUE TITLE
Ошибка ClientsDB

### ISSUE THREAD

**Issue by panches** [VasiliyM/tt-system-data#73]
Уже второй раз (на другом ПК) ловим такую ошибку в базе. Появляется сама, когда взаимодействия с ней нет. Приходится убивать процесс ибо при клике на "ОК" появляется новое окно с ошибкой.

**Comment by panches** [comment]
Уже второй раз (на другом ПК) ловим такую ошибку в базе. Появляется сама, когда взаимодействия с ней нет. Приходится убивать процесс ибо при клике на "ОК" появляется новое окно с ошибкой.

**Comment by panches** [comment]
Изучит картинку, подумал, а как они здесь оказались? И понял, что проблема зарыта на странице АКТИВНЫЕ. При привязке ТТ к СК оператор какого-то х…. сунет на страницу СК в БАЗЕ и что-то там делает, а затем жмет ВЫБРАТ в окне. Чтоб это пресечь, программа не позволит операторам при привязке ТТ покидать страничку АКТИВНЫЕ и вообще что-либо делать вне всплывшего окна. Это касается всех окон при привязке ТТ.

Это все реализовано в v5.46.04, файл выложил.

**Comment by panches** [comment]
Новая: Пользователи жалуются что поле ответственный пустое, если ты выбираешь любой фильтр (правый верхний угол) кроме  «Все» и «Документы копии»

**Comment by VsMoroz** [comment]
Ты смешал две системы в одном тикете :)  ошибка была в системе ТТ, а   отсутствие фио (на которую нет ишьюса) случилась в бух базе  в рамках задачи модернизации, добавления двух полей на основной экран
