### ISSUE TITLE
Уровни доступа к заклабке Сервисы субпровайдеров 

### ISSUE THREAD

**Issue by panches** [VasiliyM/tt-system-data#74]
Добавить поле в tab_access поле в котором будет инфо о том можно ли полозователю смотреть закладку  Сервисы субпровайдеров или нет.
В приложении это проверять и скрывать если нет.
0-  Нет доступа
1-  Читать
2-  Читать редактирова

**Comment by panches** [comment]
ккккккк

**Comment by panches** [comment]
Добавил поле:

ALTER TABLE `tab_access`  ADD `ssu_level` INT(1) UNSIGNED NOT NULL DEFAULT '2' COMMENT '0-нет доступа,1-читать,2-читать редактировать';

**Comment by panches** [comment]
Выполнил, v5.46.05

**Comment by VsMoroz** [comment]
Ок, пробуем, только давай поменяем значение по умолчанию: DEFAULT '0' 

ALTER TABLE tab_access ADD ssu_level INT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0-нет доступа,1-читать,2-читать редактировать';

**Comment by VsMoroz** [comment]
Протестил - работает, запускаю тест на группе из 5 ти человек - если все ок, обновлю у всех.

**Comment by panches** [comment]
Что бы в закладке СТОП, пользователям уровня 0 и 1 запретить копировать в буфер все что на экране , а так же убрать кнопку импорт в ексель.
v5.46.06

**Comment by VsMoroz** [comment]
Спасибо, все нормально
