### ISSUE TITLE
Окно Trouble Ticket -> Аварийки, добавить метки о типе SLA и изменить сортировку

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#75]
Пришло время добавить и сюда SLA:

Закладка Trouble Ticket -> Аварийки
1.Изменить название поля "приоритет" на "pri"

2.Поставить поле №ТТ самым первым полем слева

3.Между полями "pri" и "Поступил"  вставь поле SLA (так же как мы вставляли в Активные ТТ и обязательно с вот тем механизмом жирности который реализован в Активных ТТ

4.Измени сортировку по умолчанию, сортировать только по полю  "Поступил" desc

**Comment by panches** [comment]
Выполнил. v5.46.08, файл выложил.

**Comment by VsMoroz** [comment]
Исправляю ошибку в техзадании, сортировка по полю "Поступил"  нужно сделать ASC вместо DESC

Дополнение: сделай в закладке Аварийки, что бы при нажатии кнопки Выбрать или ОК( в написании отчета) курсор опускался на нижнюю строчку ( а то сейчас он на верхней)

**Comment by panches** [comment]
Исправил, версию не менял.

**Comment by VsMoroz** [comment]
Тест - ок,
Отправил пользователям для практического теста

**Comment by VsMoroz** [comment]
Тестовая группа  ошибок не прислала, сегодня проапдейчу приложение на всех, ишью закрываю, если будут ошибки - вернемся к нему.
