### ISSUE TITLE
Основное окно, Статистика -> загрузка -> график Записи, убрать записи автомата и от email юзеров

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#76]
Привет ! 
Давай уберем с графика "Записи" (Основное окно, Статистика -> загрузка -> график Записи)
записи от автомата и от emailов

В запрос которым ты строишь график добавь такое: WHERE `name_user` NOT LIKE 'автомат' AND `name_user` NOT LIKE '%@%'
- сам график выслал тебе почтой

**Comment by panches** [comment]
Выполнил, v5.46.09 (файл выложил)

**Comment by VsMoroz** [comment]
Супер, работает, спасибо
