### ISSUE TITLE
Trouble Ticket -> Аварийки, добавить функционал сортировки для всех полей

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#77]
Trouble Ticket -> Аварийки, добавить функционал сортировки для каждого поля, что бы по нажатию значения сортировались то по возрастанию то по убыванию.

Не сломай сортировку по умолчанию :) !!

**Comment by panches** [comment]
Выполнил, v5.46.10 (файл выложил)

Поля "sla" и "Тип наряда" искуственные (беруться не из SQL-запроса) сортироваться не будут. Для сортировки этих полей надо переделать полностью все запросы и не только, т.е. надо больше времени.

**Comment by VsMoroz** [comment]
Это не срочно, оставим пока ишью открытым.

**Comment by panches** [comment]
Сортируется по всем полям, v5.46.12

**Comment by VsMoroz** [comment]
Спасибо работает !

**Comment by VsMoroz** [comment]
Пользователи обнаружили ошибку: Выдает много ошибок и блокирует работу если нажать сортировку в когда за бригадой нет закреплено ни одного наряда

**Comment by VsMoroz** [comment]
Сортировка дает сбой если выбрать любую аварийную группу. Если не выбирать, ( в Выбор бригады стоит ВСЕ ВСЕ) только в такой ситуации сортировка работает нормально.

**Comment by panches** [comment]
Исправил ошибку, v5.46.13 (как #79)

**Comment by VsMoroz** [comment]
Спасибо, нормально все работает теперь
