### ISSUE TITLE
База -> Сервисы клиента, добавить столбик с СЛА

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#78]
Привет ! 
Прошу добавить  СЛА в закладку База -> Сервисы клиента
Назвать новое поле SLA
Разместить его между полями "Емкость" и "Офис А"
Отображение (и логику с выделением) прошу точно такую же как мы реализовали в закладке "Активные ТТ"

**Comment by panches** [comment]
Выполнил, v5.46.10 (файл выложил)

**Comment by VsMoroz** [comment]
Спасибо !
