### ISSUE TITLE
Добавить причину инцидента в email оповещение при закрытии ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#79]
- вводим понятие официальная причина (версии сейчас согласовываю с бизнесом) ее будем добавлять в шаблон письма
- добавим поле type_2_d в тт т.к. без него сложно роботу будет понять что в type_2 (при совпадениях)
- в отсылаемых версиях намечается ветвление, ранее мы согласовали формат с одним из банков, они наотрез отказываются менять свой обработчик и обрабатывать наши письма с новой информацией.
  Поэтому для них останется старый шаблон ( в каталог партнеров  я введу новое поле в котором будет видно какой шаблон использовать)

**Comment by VsMoroz** [comment]
Саша добавь 
в таблицу trubl поле type_2_d (int(3) default = 0)
в таблицу classification  добавить поле formal_version (text, default = None). Таблицу classification я пришлю почтой.

Модернизируй десктопное приложение что бы при  закрытии ТТ  ( не забудь подчиненные Тт при закрытии материнского) в type_2_d вставлялся classification.id того что инженер выбрал для внесения в  type_2

**Comment by VsMoroz** [comment]
Модернизируем серверную часть системы ТТ
Сейчас мы перейдем к двум шаблонам email рассылки, BASE и UGBK
UGBK - оставим как есть сейчаc ( это касается всех трех действий open, update, close)
BASE - будем модернизировать, а имено в шаблон close добавим причину инцидента.
1. Добавим новое поле: 

<code sql>
ALTER TABLE `tab_klients` ADD `emailtemplate` VARCHAR( 4 ) NOT NULL DEFAULT '' COMMENT 'Шаблон email оповещения' 
</code>

Пришлю тебе всю табличку готовую по email

2.Разветвить программу серверной части при формировании email оповещения по ТТ, анализировать поле tab_klients.emailtemplate если там UGBK должна выполниться рассылка как сейчас. Если там BASE код должен ответвиться и выполнять email оповещение по другому шаблону.
В этом BASE шаблоне мы пока меняем часть отсылаемую по закрытию ТТ, добавляем слово "Причина" и подставляем официальную причину. Причину можно получить таким запросом:

<code sql>
SELECT classification.formal_version as prichina
 FROM trubl
  JOIN classification ON  trubl.type_2_d = classification.id
 WHERE trubl.num_of_trubl_tick = 'здесь номер тт'
 LIMIT 1 
</code>

Пример:

```
TT: #342 476 - Close 
20.01.16 10:50 (UTC+2)
Причина:  "здесь причина"
-------
```
- позже мы модернизируем часть open  в email оповещении.

**Comment by VsMoroz** [comment]
Давай браться за эту задачу:

**Comment by panches** [comment]
Давай возьмемся. Новые поля уже добавил.

**Comment by VsMoroz** [comment]
Выслал заполненную таблицу classification

**Comment by panches** [comment]
Вопрос по серверной части:
Есть №№ТТ, они могут быть ТП, СС, СУ и т.д. Какие правил при ветвлении? Как прейти к tab_klients?

**Comment by VsMoroz** [comment]
Если ТТ открыт на СК и ОК - то инфо о профиле оповещения берем из tab_klients (завтра я вышлю эту табличку с заполненными профилями оповещения)
Если ТТ открыт на что либо другое используем профиль BASE

**Comment by panches** [comment]
Для профиля BASE надо "причина". Наверно ты имел в виду профиль UGBK?

**Comment by VsMoroz** [comment]
Причину мы возьмем вот таким запросом из ТТ 
SELECT classification.formal_version as prichina FROM trubl JOIN classification ON trubl.type_2_d = classification.id WHERE trubl.num_of_trubl_tick = 'здесь номер тт' LIMIT 1

**Comment by panches** [comment]
Выполнил клиентскую часть, v5.46.13

**Comment by panches** [comment]
Выполнил серверную часть, v2.0.2

**Comment by VsMoroz** [comment]
Добавь в клиента, в закладку Trouble Ticket -> Зарытые ТТ,  сразу за словом Классификация: фразу: (Клиент будет извещен версией: вставить официальную версию из classification.formal_version ) 
Что бы эта надпись появлялась и обновлялась всегда после выбора type_2 в интерфейсе
Почтой пришлю скриншот.

**Comment by VsMoroz** [comment]
Версия 2.0.2 не работает, вообще. Проверял ее у себя ?
Это походу совсем другая версия у нее все другое. Она наверное сырая очень.
Сейчас пишет что Unknown MySQL data type

**Comment by panches** [comment]
Заменил файл, должно заработать (проверял через VPN)

**Comment by panches** [comment]
Добавил, v5.46.14

**Comment by VsMoroz** [comment]
v5.46.14, сама фукция отображения работает, но выбирает официальные версии некорректно.
 я выбираю "Сторонний оператор" "авария по электропитанию", 
в таблице classification.id =15 должно подтянуться "Авария по электропитанию на узле связи"

Но подтягивается почему то :  авария по электропитанию

**Comment by panches** [comment]
Исправил, версию не менял

**Comment by panches** [comment]
Серверная часть, v1.9.17

**Comment by VsMoroz** [comment]
Добавь пожайлуста  в формы редактирования и добавления  Партнера, Поле " Шаблон email оповещения.
Доступ на его редактирования только 5 тому уровню
По умолчанию значения BASE
Поле соеденено с emailtemplate

**Comment by VsMoroz** [comment]
Проверь при закрытии материнского (или переводе его в статус У) в подчиненные тоже вставляется type_2_d ? Должен вставляться.
Почтой пришлю пример.

Апдейт, хотя нет.. в материнском тоже нет официальной версии, возможно пользователь использовал старую версию программы, но все равно проведи ревизию этого момента.

**Comment by panches** [comment]
При закрытии "материнского" в него и в подчинненные ТТ добавляется значение в type_2_d.
При переводе "материнского" в статус У изменение вносится только в поле state_tt.

**Comment by VsMoroz** [comment]
> При закрытии "материнского" в него и в подчинненные ТТ добавляется значение в type_2_d.

Это проверено, это на 100% верно ?

При переводе материнского в статус У, если у него есть подчиненные  сервер или программа  работает с ними как с подчиненными при закрытии материнского, инженеру предлагает заполнить type_1 и type_2  и дату окончания ТТ. Проверь в таком случае в материнский и подчиненные должно внестисть так же и type_2_d

**Comment by panches** [comment]
Не помню по каким причинам, но блок где добавляются записи (!) к подчиненным заблокирован в коде. И все, что заполняется никак не используетя. Но в скобках там записано: закрытием и вывидением из подчинения занимается сервер!!!

**Comment by VsMoroz** [comment]
Давай поработаем с сервером :) Мы скорей всего сделали это изза ошибок в клиентах которые могут быть запущены на непойми каких машинах, а серверная часть запущена ближе к БД и работает стабильней

**Comment by panches** [comment]
Да, похожа такая мысль и была причиной.

**Comment by panches** [comment]
v5.46.16. Поле " Шаблон email оповещения" добавлено.
.

**Comment by VsMoroz** [comment]
Проверил нормально все. Для окончания задачи нужно модернизировать сервер, что бы он при работе с подчиненными так же оперировал с type_2_d

**Comment by panches** [comment]
v1.19.17. Добавил поле type_2_d для подчиненных в таких пп. сервера:
- Распределять подчиненные ТТ в очереди
- Стататус "материнского" = уведомление - подчиненные в очередь
