### ISSUE TITLE
CID уменьшить вероятность дубляжей 

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#80]
Привет ! 
В системе ТТ необходимо уменьшить вероятность появления CID дубляжей:
1. Форма редактирования СК - позволить редактировать поле CID только пользователям уровня 2 и 5, для остальных поле  должно быть r/o
2. При нажатии кнопки сохранить в форме редактирования СК, проверять ниже приведенным запросом, если запрос выдает значение - показывать  предупреждение "Такой CID закреплен за услугой: и  показывать услугу которую покажет запрос.

<code sql>
SELECT CONCAT('CID: ',CID,', ',GetNameOfClient(7,net_data.id_data))  AS info
  FROM net_data 
  WHERE CID like 'значение из подя CID в форме редактирования клиента' AND `status_d` = '2' 
  LIMIT 1
<code>

**Comment by panches** [comment]
Выполнил, v5.46.11

**Comment by VsMoroz** [comment]
Не назначал эту задачу тебе :) давай доделаем все задачи по реестру счетов, а потом возьмемся за систему ТТ !

**Comment by VsMoroz** [comment]
Протестил, не годится, оно сейчас выдает предупреждение но изменение в CID  сохраняет.
Нужно что бы если обнаружен дубляж сохранение не происходило, просто всплывало окно предупреждения и пользователь после нажатия ок мог подредактировать. А сохранение происходило бы только если нет дубляжа

**Comment by panches** [comment]
А в этот список редактируемая запись случайно не попадает?

**Comment by VsMoroz** [comment]
Не, я взял две записи, и в нижнюю попытался вписать CID верхней, оно выдало предупреждение что такой СИД уже занят,   я нажал на нем кнопку ОК он все сохранил форму редактирования закрыл. Все в системе две разных записи с одинаковым CID

**Comment by panches** [comment]
Это ход понятен. Это если есть две записи с одинаковым СИД.
А если СИД один. Запрос покажет эту записть? И закрыть можно только поменяв правильный СИД.

**Comment by VsMoroz** [comment]
Ага и тут проблема есть, если ты просто нажмешь редактировать СК ничего не меняешь, сохраняешь и получаешь извещение  о дубляже и потом сохраняется.
Давай поменяем запрос:
<code sql>
SELECT CONCAT('CID: ',CID,', ',GetNameOfClient(7,net_data.id_data))  AS info
  FROM net_data 
  WHERE CID like 'значение из подя CID в форме редактирования клиента' AND `status_d` = '2'  AND net_data.id_data != 'id_data которую редактируешь'
  LIMIT 1
<code>

**Comment by panches** [comment]
Предлазаю такой запрос:

SELECT CONCAT('CID: ',CID,', ',GetNameOfClient(7,net_data.id_data)) AS info FROM net_data WHERE CID like 'значение из подя CID в форме редактирования клиента' AND status_d = '2' AND id_data <> 'id_data редактируемой записи' LIMIT 1

**Comment by VsMoroz** [comment]
;) конечно

**Comment by panches** [comment]
Измени SQL-запрос, версию не менял.

**Comment by VsMoroz** [comment]
Спасибо, работает, буду апдейтить

**Comment by VsMoroz** [comment]
Замени плиз название окна которое всплывает при дубляже на "Обнаружен дубляж CID"
А саму надпись в всплывающем окне подправь к такому формату:

Введите другой CID, т.к. введенный уже используется и закреплен за услугой: и показывать услугу которую покажет запрос.

SELECT CONCAT('CID: ',CID,', ',GetNameOfClient(7,net_data.id_data)) AS info FROM net_data WHERE CID like 'значение из подя CID в форме редактирования клиента' AND status_d = '2' LIMIT 1

**Comment by panches** [comment]
Изменеия выполнил, версию не менял (v5.46.12)

**Comment by VsMoroz** [comment]
Спасибо !
