### ISSUE TITLE
Шаблон оповещения BASE добавить статус ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#82]
Привет ! 
Добавь в шаблон email оповещения BASE строку Status
Получить значение статус запросом:  `SELECT tab_status_tt.forCustomer  
FROM trubl
JOIN  tab_status_tt ON trubl.status_tt  = tab_status_tt.id 
WHERE num_of_trubl_tick = 'номер тт'`

**Операция open:**
Open TT: #343 926
Status: В ожидании
### :  Какой то банк, ПД, 0,512М, (Ужгород, ул. Ужгородская - ул. Неужгородская)

CID: D717992

**Операция  update:**
12:45 Причина выясняется
 Расчетный срок окончания: 20:00 29.01

Open TT: #343 926
Status: В работе
29.01.16 12:18 (UTC+2)
### :  Какой то банк, ПД, 10М, (Ужгород, ул. Ужгородская - ул. Неужгородская)

CID: D717992

**Операция  close:**
TT: #343 926 - Close 
01.02.16 09:11 (UTC+2)
Причина: Пользователь временно отключил свое оборудование`

12:45 Причина выясняется
 Расчетный срок окончания: 20:00 29.01

Open TT
Status: Решен
### :  Какой то банк, ПД, 10М, (Ужгород, ул. Ужгородская - ул. Неужгородская)

CID: D717992

**Comment by panches** [comment]
v1.9.18, добавил статус ТТ.

**Comment by VsMoroz** [comment]
Статус отображается нормально, спасибо.
