### ISSUE TITLE
Ввести в систему ТТ понятие прогнозирование причины и сроков инцидента с учетом сроков SLA

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#83]
Введем в систему ТТ сущность "прогнозирование причины и сроков инцидента".
Что бы в ТТ инженер мог их ввести  (и они отослались клиенту).
Обязательно контроллировать сроки внесения  причины  согласно SLA .

**Comment by VsMoroz** [comment]
- Займемся этим после добавления статусов в BASE шаблон email оповещения.

1.Добавим trubl.estimate_of_end в котором будет содержаться оценочный срок окончания ТТ:
`ALTER TABLE trubl ADD estimate_of_end DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Оценка, времени оконч.ТТ' AFTER tab_on`

Отработаем интерфейс на материнских ТТ, затем включим его для всех ТТ с SLA:
2.(пришлю картинку) Заменить "Официальная версия, заполнять когда ТТ станет 'материнским' " на "Прогнозируемые причина и сроки окончания инцидента"

   2.1 заменить поле "Срок устранения" на хороший календарик  с датой временем, если хорошего нет, пусть остается как есть сейчас, при каждом изменении официальной версии сохранять "Срок устранения" в trubl.estimate_of_end

**Comment by VsMoroz** [comment]
2.2  в интерфейс добавления записей в материнский ТТ,  Поле официальная причина сделать просто полем (без списка) и опустить ниже сделать его редактируемым только для сотрудников проработавшим больше 9 месяцев.  На его место Разместить поля type_1 type_2. При добавлении записи, если в какомто  из полей ( срок устранения аварии, type_1 type_2) изменилось значения записать значения в поля ТТ - значения в которых изменилось: estimate_of_end, type_1, type_2, type_2_d 
Так же в интерфейсе показывать строчку: Клиент будет извещен версией: сборная версия
- покажу идею картинкой

**Comment by VsMoroz** [comment]
Картинку отослал Sent: Thursday, February 4, 2016 11:16 AM
Сделаем поэтапно, сейчас добавим возможность отсылать email клиенту **для всех ТТ**

Элемент Галочка "Отослать "Что сделанно" по email клиенту" - появляется только при выполнении всех двух условий (значение по умолчанию, false):

1.Сотрудник работает больше 30 дней для обычного ТТ и больше 150 дней для материнского ТТ,  а так же и  имеет уровень доступа 0,2,5
   Для обычного ТТ Если запрос выдал >0 значит условие выполненно: 
`SELECT COUNT(*)  FROM  tab_access  WHERE  pri  IN(0,2,5) AND  DATEDIFF(NOW(), date_of_add)>30 AND id = 'id залогиненного пользователя'`

   Для материнского ТТ Если запрос выдал >0 значит условие выполненно: 
`SELECT COUNT(*)  FROM  tab_access  WHERE  pri  IN(0,2,5) AND  DATEDIFF(NOW(), date_of_add)>150 AND id = 'id залогиненного пользователя'`

2.Если этот ТТ (или подчиненные ему ТТ) имеют email адресатов
Если запрос выдал >0 значит условие выполненно: 
`SELECT COUNT(*)  FROM trubl WHERE  email_send like '%@%' AND (num_of_trubl_tick = 'номерТекущегоТТ' OR depend_on = 'номерТекущегоТТ')`

Если галочку инженер поставил (true)  то вносимой в тт записи установить такое значение поля  zapisi_trubl_tic.transition ='61', а серверная часть уже сейчас умеет работать с такими записями ее пока переделывать не нужно будет.

**Comment by VsMoroz** [comment]
Добавил запросы, посмотри.

**Comment by VsMoroz** [comment]
Скорректировал техзадание, будем позволять слать письма из ТТ для обычного ТТ если сотрудник проработал больше 30 дней, для материнского > 150 дней:

1.Сотрудник работает больше 30 дней для обычного ТТ и больше 150 дней для материнского ТТ,  а так же и  имеет уровень доступа 0,2,5

**Comment by VsMoroz** [comment]
Следующим шагом уберем из формы "добавить запись" в материнский ТТ  поле с выпадающим списком официальных версий.

Заменить надпись: "Официальная версия, заполнять когда ТТ станет 'материнским' " на "Прогнозируемые причина и сроки окончания инцидента"

 Заменить поле "Срок устранения" на хороший календарик с датой временем, если хорошего нет, пусть остается как есть сейчас, при каждом изменении официальной версии сохранять "Срок устранения" в trubl.estimate_of_end

Добавить (как при закрытии ТТ) поля Type_1 и type_2 а так же надпись о  том как это будет сообщено клиенту (так же как при закрытии ТТ)

Записывать значения в поля Type_1 type_2 trubl.estimate_of_end если значение в каком либо из этих полей изменилось.
А так же вносить в ТТ запись ( по полной аналогии как мы делаем сейчас с zapisi_trubl_tic.transition ='61') где будет официальная версия клиенту и срок устранения но с zapisi_trubl_tic.transition ='63'
- дальше будет доделывать сервер что бы он в оповещение клиента в процесс update  отсылал  все записи zapisi_trubl_tic.transition ='62' и только последнюю запись с zapisi_trubl_tic.transition ='63' или 64

После отправки сообщения клиенту все 61 станут 62, а все 63 станут  64.

**Comment by panches** [comment]
Вопрос по отсылки письма для простого ТТ:
в запись в поле desc_zapisi добавляется  Причина т Предполагаемое время, где мне их брать или что туда писать?

**Comment by VsMoroz** [comment]
Серверная часть переварит, пример ниже:  (мы серверную часть потом переделаем как следует, после того как десктопную сделаем) Пока давай сделаем только десктопную.

Вот я добавил такую запись: 
`INSERT INTO`zapisi_trubl_tic`(`num_zap_trubl`,`num_trubl`,`date_zapisi`,`time_zapisi`,`desc_zapisi`,`name_user`,`kontakt`,`user_id`,`col_centr`,`transition`) VALUES
(3334087, 214525, '2016-02-05', '15:52:34', 'Проверены параметры', 'Мороз В.', 'Менеджер 4566', 0, 0, 61);`

И получил вполне себе нормальное письмо

> 05.02.16 15:52 Проверены параметры

**Comment by panches** [comment]
Я о сервере не безпокоюсь. Меня интересует, что писать в запись.

**Comment by VsMoroz** [comment]
Во внесении записи с Галочкой ничего не меняется, она записывается  в БД  как и обычная запись только   zapisi_trubl_tic.transition ='61'

**Comment by panches** [comment]
Поясню: в "материнском" ТТ появляется форма, где вносится инфа о причине и времени. Эта инфа вносится в поле desc_zapisi. В "простом" ТТ такой формы нет, и инфу негде брать. Что писать в это поле?

**Comment by VsMoroz** [comment]
Аааа.,  я тебе писал о возможности слать email пользователю а ты пошел дальше. Понятно.
Давай отработаем  посылку email ( тоесть галочку)  а потом перейдем к официальной версии. Что бы поэтапно было и не путаться.

**Comment by panches** [comment]
v5.46.17
Выполнел: механизм с "галочкой", изменил поля в форме "предполагаемого окончания", добавляет время в поле estimate_of_end и заполняет поля  type_1 type_2, а также поле master_info.

**Comment by VsMoroz** [comment]
Выглядит хорошо ! 
Давай сделаем только галочку  и механизм сохранения записи в ТТ доступным так же и для обычных ТТ.

**Comment by panches** [comment]
Это сделано, если "пользователь" проработал > 30 дней и поле email_send имеет емайл-адрес.

**Comment by VsMoroz** [comment]
Точно, так и есть.
Сделай что бы значение галочки обнулялось если я пытаюсь добавить запись в  другой ТТ, а то чейчас форма запоминает значение галочки и при попытке добавить запись галочка уже стоит, нехорошо.

**Comment by panches** [comment]
Подправил, версию не менял

**Comment by VsMoroz** [comment]
Тестирую, к тебе следующая просьба, если идет добавление записи с установленной галочкой в материнский ТТ, точно такие же записи добавлять и в подчиненные ТТ у которых есть email адресаты.
- Напомни, раньше если добавлялась причина аварии в материнский ТТ, эта же причина добавлялась в подчиненные ТТ с email силами клиента или силами сервера ?  Описанную задачу выше нужно реализовать в такой же способ.

**Comment by panches** [comment]
Такие же записи добавляются в подчиненные у которых есть емайл, как и в материнский.

Записи в ТТ (а также в подчиненные) добавлялись и добавляются Клиентом.

**Comment by VsMoroz** [comment]
Ок, теперь вернемся к материнским.
Нужно модернизировать что бы при открытии формы добавления записи в материнский ТТ, он проверял, есть ли в материнском ТТ инфо в полях type_2_d и в estimate_of_end:
   если нет то предлагал пользователю выбрать type_1 и type_2 и срок устранения аварии и только после этого разрешать добавлять запись в ТТ

Дальше проверить:  или если выбранные пользователем type_2_d или estimate_of_end значения отличаются от записанных в ТТ то перезаписывать вТТ значения  type_1,  type_2, type_2_d, или estimate_of_end из тех которые выбрал пользователь в форме.
- Не забыть при загрузке формы добавления записи в ТТ подтянуть в нее значения прогнозируемых сроков устарениня аварии из type_2_d или estimate_of_end 

Как сделаем это, я сформирую задание на тип добавляемой в ТТ записи. Будем делать по частям

**Comment by panches** [comment]
выполнил, v5.46.18

**Comment by VsMoroz** [comment]
Спасибо ! 
ОК, давай включим возможность добавлять официальную версию и для материнских и для обычных ТТ.

Для материнских требуем введения официальной версии сразу, (не позволяем добавлять записи в ТТ пока не выберут официальную версию) 

Для обычных смотрим на наши обязательсва, если (now() - date_of_open)  в минутах  > tab_sla_net_data.firstContactIn - тогда тоже требуем выбрать официальную причину аварии если < тогда не требуем пусть все будет на совести пользователя.

Так же при добавлении официальной версии в любой ТТ(обычный или материнский) , заполнять ему master_info   в таком формате : 23:03 28.02; classification.formal_version (официальную версию поднятуть на основании type_2_d а дату на основании   estimate_of_end)

**Comment by panches** [comment]
А сейчас разве не сразу требует заполнить поле type_2?

**Comment by VsMoroz** [comment]
В материнском сразу, в нематеринском  мы планировали  давать время инженеру разораться в чем причина и после истечения срока описанного в SLA - требовать внесения

**Comment by panches** [comment]
Тогда пункт первый выполнен (Для материнских требуем введения официальной версии сразу, для обычных пока не требуем.)

**Comment by panches** [comment]
Оказывается, поле .master_info  нигде не используется!
Оно мелькает в автокоординации ТТ, но и там не используется. Вот так :)

**Comment by VsMoroz** [comment]
Добавил в техзадание проверку на срок извещения клиента согласно SLA, таблицу с SLA пришлю почтой

**Comment by panches** [comment]
Подправил поле master_info 
Добавил проверку на срок извещения клиента согласно SLA
Файл выложил, версию не менял

**Comment by VsMoroz** [comment]
Продолжим, форма добавления записи в ТТ: при добавлении или изменении Предварительной причины аварии type_1 type_2 или сроков устранения estimate_of_end 

Добавить запись в ТТ и его подчиненные ТТ (но только  в те материнские и подчиненные ТТ которые имеют Email адресатов) где: 

**zapisi_trubl_tic.desc_zapisi** = Предварительная причина:  classification.formal_version, рассчетный срок окончания trubl.estimate_of_end(в формате '12:30 13 февраля 2016')

**zapisi_trubl_tic.name_user** = Имя пользователя который внес запись

**zapisi_trubl_tic.kontakt** = '-' все равно сервер потом затрет адресами на которые отошлет.

**zapisi_trubl_tic.transition** = '63'

**Comment by VsMoroz** [comment]
При процедуре подчинения ТТ к материнскому, нужно  сначала скопировать значения type_1 type_2 status_tt  и estimate_of_end  из материнского в подчиняемый, затем если подчиняемый имеет email адресатов  внести в подчиняемый такую же дополнительную запись (как описанно сообщением выше)
- а существующий механизм при подчинении ТТ (там тоже добавляется запись в подчиняемый) можно отключить.

**Comment by panches** [comment]
Выполнил, v5.46.20

**Comment by VsMoroz** [comment]
Глянь я добавил что при подчинении, необходимо в подчиненный так же  скопировать  состояние status_tt  из материнского

**Comment by panches** [comment]
добавил, файл выложил

**Comment by VsMoroz** [comment]
Работает, спасибо закрываю

**Comment by VsMoroz** [comment]
Отцитированная часть требует изменений:

> Для материнских требуем введения официальной версии сразу, (не позволяем добавлять записи в ТТ пока не выберут официальную версию)
> 
> Для обычных смотрим на наши обязательсва, если (now() - date_of_open) в минутах > tab_sla_net_data.firstContactIn - тогда тоже требуем выбрать официальную причину аварии если < тогда не требуем пусть все будет на совести пользователя.

 Для обычных ТТ смотрим на наши обязательсва, если 
((now() - date_of_open) в минутах)  >  tab_sla_net_data.firstContactIn \* **(умножить на 0,9)** - тогда тоже требуем выбрать официальную причину аварии если < тогда не требуем пусть все будет на совести пользователя.

Так же мы не должны требовать выбрать предварительную причину и сроки аварии для ТТ: с trubl.type_trubl_d IN (1,5,6,11)

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Спасибо, работает нормально.

**Comment by VsMoroz** [comment]
Прошу в поле Срок устранения рекомендуемое время окончания инцидента округлять к часу в сторону увеличения что бы не было 8:25, а было 9:00

**Comment by VsMoroz** [comment]
Прошу добавлять в записи с transition = 63  в конце  часовой пояс (UTC+3)

**Comment by panches** [comment]
выполнил, v5.46.38

**Comment by VsMoroz** [comment]
Часовой пояс вижу, не забудь про округление времени окончания инцидента.
