### ISSUE TITLE
Вывести из эксплуатации кнопку "Отложить" в закладке активных ТТ

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#84]
Вывести из эксплуатации кнопку "Отложить" в закладке активных ТТ
Кнопку пока оставим на месте, отключим всю логику и при ее нажатии - показывать пользователю информационное окно:

"Добрый день ! Вы можете отложить ТТ щелкнув правой кнопкой мыши на ТТ и выбрав в меню "Статус -> Пауза, партнеры (или Пауза, Клиент)" 
Пауза, клиент - выбирайте если мы ждем чего либо от клиента (решения или действия)
Пауза, партнеры - выбирайте если мы ждем чего либо не от клиента.
- Не срочно :)

**Comment by panches** [comment]
выполнил, v5.46.18

**Comment by VsMoroz** [comment]
Гуд, спасибо !!

**Comment by VsMoroz** [comment]
В информационном окне попутаны местами описания

*_Вместо: *_
Пауза, клиент - _выбирайте если мы ждем чего либо от клиента (решения или действия)_
Пауза, партнеры - выбирайте если мы ждем чего либо не от клиента.

*_Написано: *_
Пауза, партнеры -  _выбирайте если мы ждем чего либо от клиента (решения или действия)_
Пауза, клиент - выбирайте если мы ждем чего либо не от клиента.

Прошу упорядочить описание статусов как в исходном техзадании

**Comment by panches** [comment]
исправил, v5.46.22

**Comment by VsMoroz** [comment]
Привет, просьба сделать отфильтровку ТТ которые стоят на паузе в закладке: Статистика -> Нагрузка, график  " Открытые ТТ по направлениям" и "Всего открыто ТТ и по секторам" просто добавь в запрос в раздел WHERE вот это: " AND  trubl.status_tt NOT IN (3,4)"

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Спасибо !
