### ISSUE TITLE
Добавить новые параметры SLA при двойном щелчке на Активный ТТ или на СК

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#85]
Прошу в информационную форму (всплывает при двойном щелчке на Активный ТТ, на запись в СК и на Задачу в Аварийках) добавить информацию о сроках устранения аварии,  времени первого контакта, если выбрано то предполагаемых причинах и сроках инцидента.

Пример:
**CID:** D172461, **SLA:** Партнерський (ptn), **срок устранения:** tab_sla_net_data.timeframe ч., **первый контакт** через: tab_sla_net_data.firstContactIn/60 ч. (округлить до 0,1)
**Предварительная причина:** type_1 type_2 (Клиенту: classification.formal_version)

**Comment by VsMoroz** [comment]
Немного изменил тех.задание:
Было: **Предварительная причина:** type_1 type_2
Стало: **Предварительная причина:** type_1 type_2 (Клиенту: classification.formal_version)

**Comment by panches** [comment]
Выполнил, v5.46.21

**Comment by VsMoroz** [comment]
Глянь почту, не подтягивается версия для клиента.

**Comment by panches** [comment]
Исправил, версию не менял

**Comment by VsMoroz** [comment]
Спасибо, нормально  работает
