### ISSUE TITLE
Десктоп приложение, не передавать отложенные по новому ТТ при разлогинивании оптом.

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#86]
При вылогинивании, пользователь десктопной версии  имеет возможность  передать все закрепленные за ним ТТ оптом, он просто указывает в какую закладку передать и все ТТ передаются. Кроме отложенных.

Добавь в запрос который выбирает ТТ для оптовой передачи ниже приведенный код, он отфильтрует ТТ которые отложенны по новому методом статусов, что бы они оптом при отлогинивании никуда не передавались.

`AND trubl.status_tt NOT IN(3,4)`

**Comment by panches** [comment]
Выполнил, v5.46.20
