### ISSUE TITLE
Модернизация email рассылочной части сервера под новые записи в ТТ (индекс 63, 64,) и изменившиеся форматы индексов 61,62.

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#87]
Менять будем ту часть которая формирует email пользователям:

Процедуру update email рассылки для обоих профилей (UGBK и BASE)
Процедуру close тоже для  обоих профилей BASE и UGBK

Суть в том что бы мы при апдейте отсылали пользователю все записи которые он должен получать на email (61,62) но в виде как есть, без дописывания слова "Рассчетный срок"
И только последнюю запись о прогнозируемых сроках и причинах (63,64) 

А при закрытии мы между блоками  только отсылали   все записи которые он должен получать на email (61,62) (так сейчас в принципе и сделанно) только надо выкинуть ту часть кода которая разбирает запись и  добавляет слова "Рассчетный срок такой то" - нам нужно что бы записи показывались в виде как есть.

**Comment by VsMoroz** [comment]
Этот ишью есть частью ишью  #83, я сегодня дополню техзадание деталями

**Comment by VsMoroz** [comment]
Процесс CLOSE для обоих профилей (UGBK и BASE) его изменения минимальные
Сейчас ты в него собираешь шапку о открытии ТТ, закрытии ТТ и сообщения из ТТ с кодами 61,62 затем во всех текстаах полученных из записей 61 62 отрезаешь прогнозируемую дату окончания. 
Так вот ничего отрезать не нужно. Публикуй запись в полном виде как есть в БД

**Comment by VsMoroz** [comment]
Процесс UPDATE сейчас сервер берет шапку о открытии ТТ затем все записи 61,62 у всех кроме последней записи отрезает дату окончания инцидента, у последней записи парсится срок окончания и добавляется слово " рассчетный срок окончанияя ---------"

Изменения: сервер должен взять все записи с кодами 61,62 и только последнюю с 63,64 и все это вместе отослать клиенту в виде как есть ничего не отрезая
Затем все 61 перевести в 62, все 63 в 64. сделать пометки что они уже отправлены и проставить email адреса тому кому отправлены.

Так же в рамках этой доделки нам нужно исправить что бы некоторые записи у нас не пропадали из писем клиента (случай когда пользователь добавил две и больше записей в ТТ между отсылками писем, все кроме первой не отсылаются)

*Ниже опишу мое предложение по решениею обоих задач

**Comment by VsMoroz** [comment]
Сформировал в виде запросов

**Comment by panches** [comment]
Запрося заменил, v1.9.19

**Comment by VsMoroz** [comment]
В процессе апдейт поменяем дату время местами, так лучше читается.
04fb640a4221507287af2141acd93689b9e9a93d

Замени в запросе шапку, сделай ее такой:

`SELECT CONCAT(TIME_FORMAT(tmptable.time_zapisi,'%H:%i'),
              IF (trubl.date_of_start<>tmptable.date_zapisi,CONCAT(' ',DATE_FORMAT(tmptable.date_zapisi,'%d.%m.%y')),''),
       ', ',tmptable.desc_zapisi) as msgtext`

**Comment by VsMoroz** [comment]
Проведи ревизию процесса close в email оповещении:
Нужно что бы было так:

> А при закрытии мы только отсылали все записи которые клиент должен получать на email (61,62) (так сейчас в принципе и сделанно) только надо выкинуть ту часть кода которая разбирает запись и добавляет слова "Рассчетный срок такой то" - нам нужно что бы записи показывались в виде как есть.

А именно нужно сделать вот эту часть: только надо выкинуть ту часть кода которая разбирает запись и добавляет слова "Рассчетный срок такой то" - **нам нужно что бы записи показывались в виде как есть.**
Это для обоих профилей и для BASE  и для UGBK
Пример пришлю почтой.

**Comment by VsMoroz** [comment]
Глянь в ишью, строчкой ниже я добавил описание запросов для close запросов 7c12a2217df68aa6d55a71fdd05d7dd9871c7f99

**Comment by panches** [comment]
Добавил запросы, v1.9.21
