### ISSUE TITLE
Прогнозируемые сроки устранения аварии, сделать их покак как в СЛА

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#88]
Привет !
В рамках #83 сейчас если trubl.estimate_of_end = 0000-00-00 00:00:00 мы прогнозируемый срок окончания инцидента в приложении  выставляем (рекомендуем) как  now()+8 часов.

Пока мы не построили прогнозного робота, улучшим рекомендуемые сроки устранения аварии будем их выбирать так:
Если у ТТ нет SLA - тогда срок устранения  рекомендуемый =  now() +8 часов
Если у ТТ есть SLA - тогда срок устранения брать из граничных сроков устранения  SLA по такой формуле : trubl.date_of_open + tab_sla_net_data.timeframe(часов)

**Comment by panches** [comment]
выполнил, v5.46.22

**Comment by VsMoroz** [comment]
Работает нормально, спасибо
