### ISSUE TITLE
При закрытии ТТ закрыть возможность вводить причину (type_2) по своему усмотрению, только выбор из выпадающего списка

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#90]
Привет ! 
В рамках #83 прошу закрыть возможность вводить свой текст в type_1 и type_2 в десктоп приложении в форме закрытия ТТ
Раньше мы позволяли опытным сотрудникам вводить свою информацию в type_2, пришло время ее убрать, это мешает рассылки на вариант инженера у нас нет официальной версии.

**Comment by panches** [comment]
Сейчас эти поля ReadOnly (свой текст ввести нельзя, но можно удалить часть или все в поле). 
Как именно должно выглядеть "не возможность вводить свой текст"

**Comment by VsMoroz** [comment]
Нда, мы эту возможность убрали ранее, ок.
