### ISSUE TITLE
(не срочно) В информационное окно добавить скорость субпровайдера.

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#91]
Привет ! 
Прошу в информационное окно, (которое открывается по двойному щелчку на Активном ТТ или на записи в  СК  или на с привязанным к нему сервисом субпровайдера), добавить скорость из таблицы учета ресурсов субпровайдеров.

Взять скорость из : net_operators.speed_d
Разместить ее сразу за  "№ канала" пример пришлю почтой.

**Comment by panches** [comment]
выполнил, v5.46.25

**Comment by VsMoroz** [comment]
Спасибо, работает
