### ISSUE TITLE
Причина открытия офиса клиента во вкладке "Активные"

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#92]
В отличие от сервиса клиента, в офисе не указана причина открытия, если открыт ТТ по двойному клику с вкладки "Активные". Соответственно, тому, кто первый будет обращаться к клиенту приходится вручную набирать его имя и контактный номер.

**Comment by VasiliyM** [comment]
Ну давай дорогой друг, представляйся ☺

**Comment by who0ps** [comment]
Подумаю над этим, представляться ли.

**Comment by VsMoroz** [comment]
До завтра утра успеешь ?

**Comment by VsMoroz** [comment]
Time is up. Если передумаешь напиши мне в рабочую корп почту.

**Comment by VsMoroz** [comment]
Привет ! 
В активных ТТ, при двойном щелчке на ТТ во всплывающее информационное окно прошу добавить информацию о ТТ.
Сделать это по аналогии как это сделанно для  ТТ открытых на СК.
Модернизацию эту нужно сделать для ТТ открытых на: ОК, СС, 

В окно всплываемое по двойном щелчку на ТТ открытом на СУ(спутники юзают интенсивно) добавить Предварительные причины и сроки.

Примеры пришлю почтой.

**Comment by panches** [comment]
выполнил, v5.46.36

**Comment by VsMoroz** [comment]
После корректировок выглядит хорошо. Спасибо всем кто учасвствовал.
