### ISSUE TITLE
Автоматические ответы письмом зарубежным клиентам.

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#93]
Вчера бот отсылал зарубежному клиенту, не владеющим русским языком письма вида:

> 16:43, Предварительная причина: Авария по электропитанию на узле связи, расчетный срок окончания 16:34 25 Февраль 2016
> 
> 16:43, Аварию устранили в 16:34. Просьба проверить сервисы и подтвердить закрытия ТТ.
> 
> Open TT: #347 374
> Status: В работе
> 15:21 25.02.16 (UTC+2)

На что клиент ответил:

>  We kindly ask you again to provide the updates in English. 

Надо или сделать перевод автооповещений или исключить таких клиентов из рассылки.

**Comment by VsMoroz** [comment]
см #68
