### ISSUE TITLE
Кириллица при вставке с браузера заменяется знаками вопроса.

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#94]
При копировании текста из письма с Outlook Web App кириллица заменяется на знаки вопроса последние 5-10 версий. Как с Chrome, так и с Firefox последних стабильных версий. 
Наблюдается во всех текстовых полях программы.

Проблем с вставкой в другие программы нет.

Подобное было замечено и у других инженеров.

**Comment by VsMoroz** [comment]
Пишут что не актуально уже, закрываю вопрос
