### ISSUE TITLE
"Живой" фильтр во вкладке "Все за период"

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#95]
Во вкладке "Активные ТТ" - "Все за период" включён т.н. "Живой" фильтр, который фильтрирует ТТ на странице по мере ввода текста.

Чем больше диапазон дат - тем дольше длится фильтрация.

Так как БД не возращает результат быстрее 500мс , будет удобнее использовать фильтр после нажатия энтер.

**Comment by VsMoroz** [comment]
Прошу убрать живой фильтр ( устно обсуждали это) выполнять  выборку по нажатию на кнопку "Показать"

**Comment by panches** [comment]
Есть два пути: простой и сложный.
Простой: оставляем принцип как есть (фильтрация на компьютере клиента), только фильтрация будет после нажатия кн. Enter. Работы на 2 минуты.
Сложный: фильтровать на сервере, а это потребует переделать все запросы на этой странице. Займет кое какое время.
Выбирай?

**Comment by VsMoroz** [comment]
Мы устно обсуждали простой.
Его и нужно сделать. 
Сложный не такой и сложный, но к нему вернемся потом, если возникнет потребность

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Модернизируй отработку при нажатии кнопки "Показать" что бы выборка показывалась  и по выбранному за период и по  "Фильтр по полю клиент". Сейчас он отрабатывает только по "За период".

Я знаю что если поставить курсор в "Фильтр по полю клиент" и нажать ентер то отработает фильтр и по выбранному периоду и по  "Фильтр по полю клиент", вот так и нужно по кнопке "Показать" так будет интуитивно понятно.
Не забудь добавить что если в поле "Фильтр по полю клиент"  пусто - то показывать просто все что попало в выбранный период.

**Comment by panches** [comment]
Это дан старт сложному пути? Быстро описанный сценарий не реализуем.

**Comment by VsMoroz** [comment]
Этот алгоритм легко реализовать таким способом:
При нажатии кнопки "Показать"  проанализировать есть ли символы в  "Фильтр по полю клиент"

Если есть - выполнить то сейчас выполняется по кнопке "Показать" а потом сразу выполнить то что выполняется по нажатию Ентер в "Фильтр по полю клиент"

Если нет - выполнить только то что сейчас выполняется по кнопке "Показать"

**Comment by panches** [comment]
Пробовал, не работает. Нужно все ломать.

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Отлично ! Спасибо.
