### ISSUE TITLE
"Зона ответственности" и тип ТТ во время добавления ТТ

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#96]
Во время авторизации инженер выбирает свою зону ответственности или же во вкладке "Активные". Но во время добавления ТТ эта зона подхватывается и инженеру вручную необходимо переназначать на "Наземный сектор" - "_Вход_Очередь" (в большинстве случаев, кроме ССС).

Предлагаю в этой вкладке (Добавление ТТ) сделать зону ответвтвенности, которая не зависит от той, что инженер выбирал во время авторизации и от той, которая во вкладке  "Активные".
Сюда же можно добавить о выборе типа ТТ. По-умолчанию не выбрано ничего. Большинство открывается по обращению клиента, поэтому и стоит автоматически сразу выбирать этот тип.
Так как ранее было убрано текстовое поле "Открыл", то и заголовок убрать можно.

**Comment by VsMoroz** [comment]
Нельзя в открытый репозитарий постить скриншоты !
Все скриншоты внутренней почтой. 
Зона ответственности при создании ТТ ранее и была независимой,  проверим если вдруг опять стала зависимой исправим.

> Сюда же можно добавить о выборе типа ТТ. По-умолчанию не выбрано ничего. Большинство открывается по обращению клиента, поэтому и стоит автоматически сразу выбирать этот тип.

Какой процент этого большинства ?  20 процентов по НМС и 80 по обращению
Мне не хочется видеть там ошибки при открытии по сигналу НМС

Да там можно коечто улутчшить но не в такой способ. Нужно анализировать на что открывается ТТ, и может быть предыдущие открытые ТТ этим пользователем и на основании этих двух весов принимать решение.

**Comment by who0ps** [comment]
> скриншоты 

ОК.

По NMS открывают, в основном, на СУ, ТП или СС. На сервис или офис редко. И это, если я правильно понял, делают инженеры.

Не нашёл, чтобы CIC открывал на сервис или офис. 

Ну или по предыдущих, да.

**Comment by VsMoroz** [comment]
Честно говоря совсем не понял  месседж последнего сообщения :(
Статистику формировать на ощущениях можно, но в нашем случае есть полный доступ к системе и можно получить конкретные цифры, что происходит редко что часто.

За одобрение моего мнения -спасибо :)

**Comment by who0ps** [comment]
Тогда сформировать закономерности по собранной статистике и уже по ним надо бы предугадывать тип.

**Comment by VsMoroz** [comment]
:)

**Comment by VsMoroz** [comment]
Саша прошу в закладке "Добавление ТТ" убрать надпись "Открыл"

**Comment by panches** [comment]
убрал, v5.46.35

**Comment by VsMoroz** [comment]
Так же просьба в закладке "Добавление ТТ" значение в модуле "Выбор зоры ответственности" отвязать от такого же модуля в закладке Активные ТТ.

Пускай значение в закладке "Добавление ТТ" в модуле "Выбор зоры ответственности"  работает по такому алгоритму:
1. При старте программы пользователь выбирает зону ответственности, она записывается в закладку "Активные ТТ" и в закладку "Добавление ТТ"
2. Во время работы никто и ничто не может изменить значение в "Добавление ТТ" кроме пользователя непосредственно из закладки "Добавление ТТ".
- Конечно если в п.1 пользователь не выбрал зону ответственности - то и в "Добавление ТТ" тоже ничего не будет и пользователю при создании ТТ прийдется выбрать зону ответственности..

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Спасибо, тестирую.

Следующий шаг в закладке "Добавление ТТ" в поле "Тип ТТ" выставлять значение по умолчанию полученное с помощью запроса: bb1dc7eb3aa2c850a3cd340225095b703488368b

Он анализирует последний 25 ТТ которые открывал этот пользователь для этой таблицы и возвращает то значение которое встречается в этих ТТ больше всего

**Comment by panches** [comment]
выполнил, v5.46.35

**Comment by VsMoroz** [comment]
Работает хорошо, по началу было медленно, добавил пару индексов и стало быстро.

Подправь еще поочередность перехода по табуляциям убери из цепочки перехода по нажатию кнопки табуляция поля: Тип ТТ и Статус ТТ

**Comment by panches** [comment]
подправил, v5.46.35

**Comment by VsMoroz** [comment]
Спасибо, нормально работает.
