### ISSUE TITLE
Автообновление ClientsDB

### ISSUE THREAD

**Issue by who0ps** [VasiliyM/tt-system-data#97]
Обновление реализовано по локальному адресу (если я правильно понял). 
Те, кто подключены через VPN получают ошибки и база не обновляется. 

Кажется, уже об этом сообщали, но не видел issue.

**Comment by VsMoroz** [comment]
Я включен через vpn  и нормально обновляюсь.
Те кто включен через впн и не имеет доступ к определенным корп ресурсам - те конечно могут иметь сложности. Но все наши официальные пользователи имеют, кроме двух. Про тех двух я забочусь лично другим способом.

**Comment by who0ps** [comment]
-  База запрашивает обновление.
- ОК.
-  Окно винды "подготавливается копирование" .
- Ошибка:

> Clientsdb
> 
> Немогу выполнить ShellExecute!
> 
> ОК
- OK
-  База молча крашится.
-  Вручную запускаю, проверяю - старая версия.

**Comment by VsMoroz** [comment]
Твои права на компьютере позволяют записывать файл в папки с приложениями ?

**Comment by who0ps** [comment]
Тоже предположил это. Тогда надо перенести путь обновления в другую директорию.
К примеру c:/users/User/DG/ClientsDB или c:/users/User/APPdata/Local/ClientsDB.

**Comment by VsMoroz** [comment]
Это точно поможет ?

**Comment by who0ps** [comment]
Туда права на запись есть, в отличие от той директории, что сейчас. 
Прав не хватает даже для запуска инсталлятора, попробуй на учетке юзера, возможно получится. 

Точно не подскажу.

**Comment by VsMoroz** [comment]
Инсталлятор предлагает путь установки, попробуй поменяй на какой то другой - посмотри что будет.
Может у тебя права вообще не позволяют устанавливать, а может не позволяют только в отдельные папки.

**Comment by who0ps** [comment]
> Прав не хватает даже для запуска инсталлятора

Но некоторые портейбл программы удалось установить в папке юзера.  Те, что не просят права при запуске.

**Comment by VsMoroz** [comment]
Закриываю ишью, проблема с правами доступа юзера.
