### ISSUE TITLE
Изменения в шаблоне оповещения UGBK процедура close

### ISSUE THREAD

**Issue by VsMoroz** [VasiliyM/tt-system-data#98]
Привет прошу в шаблоне UGBK в выделенную жирным часть брать значение из date_of_end и time_of_end, раньше оно бралось из date_of_close

TT: #347 923 - Close 
**01.03.16 20:28** (UTC+2)

**Comment by panches** [comment]
Убрал, v1.9.23

**Comment by VsMoroz** [comment]
Погоди, тут нужно было данные о окончании инцидентабрать из других полей :) ничего не убирать.

**Comment by panches** [comment]
Так и сделал:
BASE = date_of_close
UGBK = date_of_end + time_of_end

**Comment by VsMoroz** [comment]
Спасибо, работает
